### ISSUE TITLE
中文翻译计划提议

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/cn.vuejs.org#1]
如题，在正式开始翻译之前，想提一下自己的想法

我留意到 1.x 的文档和之前的 0.x 相比改动还是比较大的，不论是文件结构还是文档内容。我个人倾向的翻译流程是：

1. 从 1.0.0 @fe8c5246ab5bffedd64c17be1456faa5e0b7f8c3 开始创建一个 `1.0.0-zh` 的分支，开始翻译，翻译好之后发布到 http://cn.vuejs.org
2. 在有大版本发布之前，翻译上的改动都延续使用这个分支
3. 之后每次版本发布，都：
    1. 先从原版开新的分支，如 `1.0.1-zh`
    2. 然后 merge 之前的 `*-zh` 分支 (需不需要持续在中英文间 merge？)
    3. 再 diff 两个原版 hash 之间的差异，比如[这样](https://github.com/vuejs/vuejs.org/compare/fe8c5246ab5bffedd64c17be1456faa5e0b7f8c3...85e58a52012cb133671987659ca0947291c9837a)比较 1.0.0 和 1.0.1 的差异
    4. 针对差异内容进行翻译和发布

另外：

- 分工的时候可以按照页面级别在 wiki 中列出来，然后号召更多的人来 issues 里认领
- 术语是否需要整理并统一译法?

**Comment by yyx990803** [comment]
:+1:

据我所知 @yanxyz 似乎自己有一个 fork，不过最好还是以紧跟原版为准，因为还会涉及到主题方面的改动。

分工方面，一些志愿者的翻译会有一些质量问题，因此不要让一个人多次认领。每个人对于认领的部分，单独开 PR，并且在我最终审校之前不要直接 merge。

术语肯定需要统一一下，可以先整理出一下，我来定稿。

**Comment by yanxyz** [comment]
不必那么麻烦，这两天我会全部翻译出来，目前教程部分已经翻译一半了。人多质量不好统一，校正比翻译还花精力。

关于这个 repo，我的想法是尽量控制体积，因为英文 repo 我现在都拉不下来。故不 fork 它了, 再说中英文 merge 也没多少意义，只会增大 repo 体积。这个 repo 只放 1.0 开始的中文，既不放英文，也不放旧版中文，让它放在旧 repo 之中就好。总之，都是为了控制体积。**英文与中文两个 repo 是独立的**。

更新，英文怎么弄，中文也跟着怎么弄。小版本不必开新分支，英文便没有，也不需要这么麻烦，在 github 上看看英文  repo 的更新记录，顺手就可以更新中文了——每次更新之后在 issue 中记录一下更新到的英文 commit sha。

**Comment by yyx990803** [comment]
独立的话有个问题就是不能直接 cherry-pick 原版做的无关内容的改动。或者干脆开一个 branch
直接全部放 raw markdown，我来处理两个 repo 之间的同步。

**Comment by yanxyz** [comment]
没有管理员的允许也不能添加无关的内容。还是需要构建程序，方便本地预览。

**Comment by yyx990803** [comment]
要不我压缩一下传到哪个网盘上...

**Comment by yanxyz** [comment]
用网盘就麻烦了，不能总是麻烦别人。

**Comment by Jinjiang** [comment]
网络环境这么成问题？

**Comment by yanxyz** [comment]
无关内容的改动目前看只有 layout，其它的你可以直接覆盖。

**Comment by yanxyz** [comment]
几十kb/s, 时间长了就断线了。库大了就下载不下来。

**Comment by Jinjiang** [comment]
独立 repo，没有分支，顺手更新 这样真的好么？如果真是一个人翻译我确实觉得这都无所谓，但是长时间x多人的话，项目会逐渐走向失控，这是我的看法

另外用 hexo 建站的 repo 已经足够小了吧，如果这个 repo 都拉不下来，时间长了纯 markdown 的也不好说，再开 branch 未必真正解决问题。

网盘就更变成一个人的工作了，怎么 review 怎么协作参考都是问题

**Comment by yanxyz** [comment]
其实有的时候我是想更新你的旧项目，但是还要等你 merge，我便放弃了。

**Comment by yanxyz** [comment]
协作更新的时候，还是创建分支提交 pr, 然后管理员 merge.

**Comment by yyx990803** [comment]
从长期维护的角度来看，还是 fork 比较好。你用个 vpn 再拉试试呢？

**Comment by yanxyz** [comment]
jp.vuejs.org 似乎也不是 fork

**Comment by yanxyz** [comment]
@yyx990803 那你建一个分支吧，中文翻译放在这个分支里。

**Comment by yyx990803** [comment]
开好了。`lang-zh`

**Comment by Jinjiang** [comment]
我参考了一下隔壁的 jp 项目，从 README、分支和 network 来看似乎和我们之前中文的方式很接近，主要是 master 不再保持同步了，除非有原版文档需要修改提交而不是翻译， 也没有后续通过 merge 把两边的版本对应起来。

我对这样的方式 (包括上面提到的独立分支、网盘等方式) 纠结之处在于翻译的版本和原版的 hash 对应不上，导致新人不太好判断该从哪里起步维护，我想到的办法是在原版打 tag，然后翻译以 tag 为节奏定期更新，在翻译版本上也打对应的 tag 或 branch；或者每次提交翻译时都在日志里注明本次提交和原版的某个 hash 对应。如果大家都觉得没太大必要，那不纠结也罢。

前者其实就是之前中文版的方式，至于 @yanxyz 提到的：

> 其实有的时候我是想更新你的旧项目，但是还要等你 merge，我才能提交 pr, 于是便放弃了。

这样的 merge 是任何人都可以自行操作的，无非是你在自己 repo 里 merge 之后发 PR 给我，发起一个新的 tag，所以需要 merge 的时候也是不需要等的，这种问题不是没有解，希望我们将来遇到别的问题也可以通过沟通来改善 :smile:

**Comment by Jinjiang** [comment]
> 不必那么麻烦，这两天我会全部翻译出来，目前教程部分已经翻译一半了。

如果已经快翻译好了，那不然我直接等 review 好了，如果有任何困难或需要分工我尽量配合

**Comment by yanxyz** [comment]
@Jinjiang @yyx990803 翻译完毕，可以开始校正了。

**Comment by yyx990803** [comment]
wow 效率真高，赞
