### ISSUE TITLE
图片中貌似错了？

### ISSUE THREAD

**Issue by tcdona** [vuejs/cn.vuejs.org#10]
http://cn.vuejs.org/guide/instance.html

![image](https://github-cloud.s3.amazonaws.com/assets%2F352931%2F10957767%2F5f140ed0-83a2-11e5-8c57-4f500c82a23f.png)

has el options yes 和 no 反了

**Comment by yyx990803** [comment]
右边那个意思是需要等待手动调用 vm.$mount().

**Comment by zuoRambo** [comment]
看来我也误会了
