### ISSUE TITLE
Vue.compile() 这个api的翻译不准确，会误导人

### ISSUE THREAD

**Issue by lujing2** [vuejs/cn.vuejs.org#1035]
目前中文文档中翻译成：
在 render 函数中编译模板字符串。只在独立构建时有效。

英文文档是：
Compiles a template string into a render function. Only available in the full build.

建议翻译成：
将一个模板字符串编译成render函数。只在full build的时候可用。

**Comment by Justineo** [comment]
欢迎提交 PR 👍

**Comment by lujing2** [comment]
没法push 我自己的分支到仓库怎么整



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GU Yiling"<notifications@github.com&gt;; 
发送时间: 2019年12月12日(星期四) 下午5:15
收件人: "vuejs/cn.vuejs.org"<cn.vuejs.org@noreply.github.com&gt;; 
抄送: "飞翔"<2457309846@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vuejs/cn.vuejs.org] Vue.compile() 这个api的翻译不准确，会误导人 (#1035)




欢迎提交 PR

**Comment by mactanxin** [comment]
@lujing2 介意我用您的翻译提交一个PR么? 😃

**Comment by lujing2** [comment]
我在我本地分支上改动了很多，不知怎么提交pr，你有权限push本地分支到远程吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xin Tan"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 下午4:51
收件人: "vuejs/cn.vuejs.org"<cn.vuejs.org@noreply.github.com&gt;; 
抄送: "飞翔"<2457309846@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [vuejs/cn.vuejs.org] Vue.compile() 这个api的翻译不准确，会误导人 (#1035)




@lujing2 介意我用您的翻译提交一个PR么? 😃

**Comment by Justineo** [comment]
@lujing2 你需要 push 到你自己 fork 的项目，然后再从那里发起 pull request。

**Comment by lujing2** [comment]
哦哦 我试试 我先fork 然后将改动push 然后再发pr




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GU Yiling"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上6:36
收件人: "vuejs/cn.vuejs.org"<cn.vuejs.org@noreply.github.com&gt;; 
抄送: "飞翔"<2457309846@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [vuejs/cn.vuejs.org] Vue.compile() 这个api的翻译不准确，会误导人 (#1035)




@lujing2 你需要 push 到你自己 fork 的项目，然后再从那里发起 pull request。

**Comment by Jinjiang** [comment]
closed due to #1039
