### ISSUE TITLE
模板编译 这个部分 中文文档链接没有显示

### ISSUE THREAD

**Issue by mablevi** [vuejs/cn.vuejs.org#1041]
模板编译
你可能会有兴趣知道，Vue 的模板实际上被编译成了渲染函数。这是一个实现细节，通常不需要关心。但如果你想看看模板的功能具体是怎样被编译的，可能会发现会非常有意思。下面是一个使用 Vue.compile 来实时编译模板字符串的简单示例：

{% raw %}

<script async src="https://jsfiddle.net/phanan/5h0wx9np/embed/result,js,html/"></script>
{% endraw %}

https://cn.vuejs.org/v2/guide/render-function.html#%E6%A8%A1%E6%9D%BF%E7%BC%96%E8%AF%91

链接有问题。文档上没有显示，建议修复下

**Comment by nowdothat** [comment]
同求

**Comment by canvs** [comment]
看了下是个iframe 里面有个jsfiddle地址
http://jsfiddle.net/5h0wx9np/embedded/result,js,html/?username=phanan

**Comment by Jinjiang** [comment]
jsfiddle 的例子已经全部换成了 codesandbox
