### ISSUE TITLE
v-on:keyup.enter方法不支持空格结束的输入

### ISSUE THREAD

**Issue by aiyi-touxiang** [vuejs/cn.vuejs.org#107]
刚开始学习vue发现这样一个问题，v-on:keyup.enter 只支持以enter键结束的输入方式，如果是空格键结束的输入是不能捕获的，但是改成v-on:keyup后是会监听的任意按键的，但是是实时的，是否可以在v-on:keyup.enter方法的处理上加上对空格按键的识别。（操作系统：OS X EI Caption，版本10.11.4，浏览器：chrome 版本 50.0.2661.86 (64-bit)）

**Comment by yanxyz** [comment]
```js
<input v-on:keyup.enter="submit" v-on:keyup.space="submit">
```
