### ISSUE TITLE
关于 ref 的译法讨论

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/cn.vuejs.org#1084]
如题，目前我们把 ref 翻译成了“引用”，但我个人觉得 ref 在逐渐演变成一个像“prop”一样的特有名词，所以倾向于在一个适当的时机将其恢复成为英文原文。

这里希望得到大家的更多意见和反馈。

谢谢

**Comment by aomiba** [comment]
附议，这个词很常见了。
引用容易让我想到 js的原始类型和引用类型
