### ISSUE TITLE
slots() vs children 给的演示代码不能工作，而且文字说明和实际运行不符合

### ISSUE THREAD

**Issue by smartisantt** [vuejs/cn.vuejs.org#1090]
[官网地址](https://cn.vuejs.org/v2/guide/render-function.html#slots-%E5%92%8C-children-%E5%AF%B9%E6%AF%94)
```vue
<my-functional-component>
  <p v-slot:foo>
    first
  </p>
  <p>second</p>
</my-functional-component>
```
1. 这段代码不能正常的工作，原因`v-slot`的使用范围在`template`元素和 组件上使用，无法在p元素使用`v-slot`
2. 如果代码是一个正常的代码， children 不是返回两个p元素，实时上只返回了第二个p元素
3. 如果代码是一个正常的代码，`slots().default`只会传递第二个匿名标签，说法不是很准确，而是有具名的且名字是defautl插槽会优先传递，如果没有的话才是匿名的。 #

**Comment by Justineo** [comment]
See also: https://github.com/vuejs/vuejs.org/issues/2110
