### ISSUE TITLE
新增不同地區的中文版本

### ISSUE THREAD

**Issue by hms5232** [vuejs/cn.vuejs.org#1096]
同樣都是中文，不同地區有不同的用語習慣差異，更不用說原先就有繁簡差異。

**建議官方新增不同地區的文件版本**，例如：中文（中國）、中文（臺灣）、中文（港澳）……等版本。
如果有的話，對於推廣 Vue 絕對不是壞事。

**Comment by Jinjiang** [comment]
https://github.com/vuejs/vuejs.org/issues/2015
可以移步这里发起或参与。谢谢🙏
