### ISSUE TITLE
改进英式中文

### ISSUE THREAD

**Issue by youngquan** [vuejs/cn.vuejs.org#1102]
今年读到一篇文章：《余光中：怎样改进英式中文？——论中文的常态与变态》，对其中提到的中文表达“西式化”的概念有了一个初步的认识。

今天在读 Vue 中文文档的时候，便总能感觉到一股从英文翻译过来的生硬味道，一点都不符合中文表达的习惯。

水平有限，我试着举几个例子：

> 已经会了 HTML、CSS、JavaScript？即刻阅读指南开始构建应用！

- 只需掌握 HTML、CSS 和 JavaScript，便可以快速构建新的应用！

> 与其它大型框架不同的是，Vue 被设计为可以自底向上逐层应用。

- 与其它大型框架不同，Vue 可以被逐步应用。

> Vue 的核心库只关注视图层，不仅易于上手，还便于与第三方库或既有项目整合。另一方面，当与现代化的工具链以及各种支持类库结合使用时，Vue 也完全能够为复杂的单页应用提供驱动。

- 一方面，Vue 的核心库只关注视图层，易于上手，便于和第三方库或者已有项目整合。另一方面，Vue 可以和前端开发工具链以及第三方支持库结合使用，从而快速开发复杂的单页应用。

考虑到 Vue 在中国的流行，个人觉得 Vue 的中文文档不是个很好的示范，因此提出这个 ISSUE，希望参与翻译的人能够意识到这个问题，从而改善 Vue 中文文档的质量。

**Comment by Justineo** [comment]
Hi，说说我的看法。首先感谢你对项目的关心。翻译也是一种创作，标准见仁见智。意译虽然可以更符合中文的表述习惯，但是这个度会非常难掌握。不同人看同一段意译的文字可能产生更大的一件偏差。如果使用直译，我个人感觉是更为“可控”。这个翻译项目是一个社区驱动的志愿工作，参与者包括项目的 owner 本身也大概率不是专业的翻译工作者。诚然客观上必然存在更“完美”的翻译，但是对项目的翻译质量提出更高的要求我感觉有一点“何不食肉糜”的味道。这个项目目前的翻译工作是很多人贡献和迭代的结果，大家水平层次不齐，可能有些内容最开始甚至是表意不清甚至错误的。我们在日常的更新中实际上也在小范围使用意译，但如果要对所有文本进行这样的处理，我认为目前没有这个可行性。你可以去翻阅一下之前的 PR 以及相关的评论，我们并不是“没有意识到”“这个问题”，并且也会想办法改善表达的文字使用习惯。希望你也可以参与进来，把意见转换为 PR，直接帮助项目进行改善。谢谢。

（但是提前说一句，采取更多的意译必然会融入更多的主观表达，产生更多意见上的分歧。）

**Comment by zmheang** [comment]
我认为 对于技术文档而言，更重要的是准确，所以尽可能的对比原文翻译或许会更好，这样我们在不同语种之间交流的时候也会少一些不必要的解释
