### ISSUE TITLE
Has the translation of vue3 started? How to contribute?

### ISSUE THREAD

**Issue by misitebao** [vuejs/cn.vuejs.org#1109]
I want to participate in the translation of Vue next. How can I join it? V3 website address: https://v3.vuejs.org/

**Comment by mcdongWang** [comment]
+1

**Comment by Hew007** [comment]
shafa

**Comment by xland** [comment]
我也想参与翻译

**Comment by softboy99** [comment]
+1

**Comment by Jinjiang** [comment]
Currently, there are still a lot of places updated every day. So we'd like to start the translation when the docs are stable enough. And I will leave a comment here at that time. Thanks.

**Comment by misitebao** [comment]
> Currently, there are still a lot of places updated every day. So we'd like to start the translation when the docs are stable enough. And I will leave a comment here at that time. Thanks.

@Jinjiang OK, thank you for your reply. Thank you

**Comment by Jinjiang** [comment]
All, please see https://github.com/vuejs/docs-next-zh-cn
Thanks.
