### ISSUE TITLE
我把Vue3 中文文档翻译好了，看下怎么合并和做后续的维护和完善。

### ISSUE THREAD

**Issue by veaba** [vuejs/cn.vuejs.org#1116]
Vue 3 中文文档：https://v3.datav.ai/
Vue 3 中文文档（备用）：https://v3.vuejs.ai/
仓库：https://github.com/veaba/docs-next 

架构现在这个cn.vuejs.org 可能不太一样。
不过，是和英文主站一个仓库clone 出来，使用vuepress

看下后续怎么发起PR啊。

四年前有幸参与了Vue2的一个响应式章节，在那之后的四年后的现在，再次看到自己曾经翻译过的文档，泪目。

Vue 2 中文文档贡献：https://cn.vuejs.org/about/
Vue 3 中文文档贡献：https://v3.datav.ai/about.html

> 勿喷，个人水平有限。

:sob:

**Comment by misitebao** [comment]
Wocao New Bee！！！

**Comment by lishizhi** [comment]
New Bee！！！

**Comment by ShenQingchuan** [comment]
为什么打不开了？

**Comment by veaba** [comment]
> 为什么打不开了？

可以的，有点慢，gh-pages 部署的。

**Comment by Jinjiang** [comment]
@veaba 首先非常感谢！由于英文文档还一直在不断更新和挑战，所以想确认一下这个翻译是基于英文文档的哪个版本(也就是你翻译时英文版当时最新的 commit hash)，以便我们具体考量和后续维护。

**Comment by veaba** [comment]
> @veaba 首先非常感谢！由于英文文档还一直在不断更新和调整，所以想确认一下这个翻译是基于英文文档的哪个版本(也就是你翻译时英文版当时最新的 commit hash)，以便我们具体考量和后续维护。

最新8月14日同步了官方master 这个commit：[docs: Update non-props attributes link](https://github.com/veaba/docs-next/commit/0a81cebd0dfd0529791230c95b4349123bafe5b6)、commit hash：[0a81ceb](https://github.com/vuejs/docs-next/commit/0a81cebd0dfd0529791230c95b4349123bafe5b6) 。

最早开始是基于commit：[Reword preference of Vue Testing Library over Vue Test Utils (vuejs#330)](https://github.com/veaba/docs-next/commit/058386ad5585a140b98a32e269c40a131826d588)、hash：[058386a](https://github.com/veaba/docs-next/commit/058386ad5585a140b98a32e269c40a131826d588)

**Comment by pruidong** [comment]
仰望大佬!😄

**Comment by BlueHusky** [comment]
古德古德   厉害厉害
![image](https://user-images.githubusercontent.com/38274463/90467911-e3437d00-e147-11ea-98cf-baf016a425f8.png)

**Comment by Aaronwn** [comment]
网站打开速度有点慢

**Comment by veaba** [comment]
> 网站打开速度有点慢

试试这个：https://v3.vuejs.ai/

**Comment by zhaozhe0831** [comment]
@veaba 首先感谢大佬了。是这样的，我翻译了“迁移策略”其中的一部分内容，发到掘金上了。我是参照谷歌和有道来翻译的，所以翻译质量估计不是很高。如果用的上的话，可以直接拿去。[我的掘金主页](https://juejin.im/user/2770425031695415)

**Comment by veaba** [comment]
> @veaba 首先感谢大佬了。是这样的，我翻译了“迁移策略”其中的一部分内容，发到掘金上了。我是参照谷歌和有道来翻译的，所以翻译质量估计不是很高。如果用的上的话，可以直接拿去。[我的掘金主页](https://juejin.im/user/2770425031695415)

客气，官方cn文档也快出来，以上面仓库为基础，到时会要邀请社区参与，把文档做的更好。

**Comment by Jinjiang** [comment]
All，经过一定的考虑和前期准备工作，我们决定采纳 @veaba 的翻译工作，并基于 @veaba 的这个仓库创建了官方的 3.0 中文文档：
https://github.com/vuejs/docs-next-zh-cn

网站目前还是有很多翻译和校对的工作要做，希望更多人可以一起参与进来！谢谢大家的支持🙏
也再次感谢 @veaba 做出的贡献！

这个 issue 我先关掉了，欢迎大家移步至新仓库
