### ISSUE TITLE
举报小贴画www.smallsticker.com

### ISSUE THREAD

**Issue by yibhou** [vuejs/cn.vuejs.org#1118]
我在 [Vue 中文官网](https://cn.vuejs.org/) 的导航栏 **"支持 Vue" -> “贴纸”**，进入了小贴画的网站（8月20号）购买了 Vue 贴纸 ，但迟迟没有收到货，然后去小贴画的官网客服、微信公众号以及它的淘宝店铺咨询客服，一直没有得到有用回复，甚至直接已读不回。

![image](https://user-images.githubusercontent.com/10102594/92068485-a8914400-edd9-11ea-8ecd-495238b29e44.png)

为何放个服务态度如此恶劣的第三方链接到官网来坑骗那些支持 Vue 的开发者！

**Comment by JobbyM** [comment]
支持维权

**Comment by yyx990803** [comment]
这家公司以前貌似还是正常运作的，这个情况对于我们来说也是意外。我正在和店主沟通看看到底是怎么回事。

**Comment by igigi** [comment]
我就是小贴画店主，最近没收到咨询问题，看这个支付金额，我们也没未发货的这样的金额的订单，请@yibhou，直接联系我们，我们实时在线，等你反馈，提供一下手机号，或者邮箱，我们排查一下，就别麻烦尤雨溪了，谢谢！

**Comment by yyx990803** [comment]
那还麻烦你们私下沟通了，这里就关了。

**Comment by yibhou** [comment]
@igigi 你好，我已经在公众号和淘宝店联系你们了，望回复

**Comment by phpdever** [comment]
@igigi 2023.02.03 下的订单，至今未发货；邮箱联系不上
