### ISSUE TITLE
vuejs.org.cn的证书链不完整，ssl配置存在问题

### ISSUE THREAD

**Issue by lqf96** [vuejs/cn.vuejs.org#112]
之前尝试把vuejs.org.cn添加到https everywhere的时候发现的...
现在vuewjs.org.cn用的le的证书，但是貌似没有包含let's encrypt authority x3这一中级证书，所以在没有缓存该证书的设备上浏览会出现警告，
用ssllabs检查过后发现除此之外还有一些别的问题，希望修正。
https://www.ssllabs.com/ssltest/analyze.html?d=vuejs.org.cn

另外www.vuejs.org.cn好像没出现在证书san中，可以考虑去掉这个域名或者用le重新生成一下...

**Comment by yanxyz** [comment]
vuejs.org.cn 网站是放在 coding.net 上，应该是它的问题。你可以试试 cn.vuejs.org，这个是放在 github 上。vuejs.org.cn 国内访问快点。

**Comment by lqf96** [comment]
嗯，也许可以跟coding反应一下，看来可能是它们paas共有的问题...

**Comment by yanxyz** [comment]
目前 coding.net 也不稳定，暂时放它那而已。

**Comment by llcrun** [comment]
hello;
https://cn.vuejs.org访问证书过期。
![WechatIMG972](https://user-images.githubusercontent.com/27272266/71074544-709b8f80-21bd-11ea-910a-0c5faa2dd788.png)

**Comment by Justineo** [comment]
@llcrun 

我这边无法复现：
![image](https://user-images.githubusercontent.com/1726061/71079180-b6f4ec80-21c5-11ea-96be-04b2207a84d6.png)

**Comment by llcrun** [comment]
现在我们这边也好了，可以正常访问了，谢谢。




| |
lzw
邮箱：llcrun@163.com
|

Signature is customized by Netease Mail Master

在2019年12月18日 18:39，GU Yiling 写道：

@llcrun

我这边无法复现：
