### ISSUE TITLE
Vue 3 Docs are ready for translation!

### ISSUE THREAD

**Issue by bencodezen** [vuejs/cn.vuejs.org#1123]
Hello! Just wanted to let you know that v3 docs are ready to start translating.

https://github.com/vuejs/docs-next

If you have any questions, please feel free to file an issue so we can help however we can!

**Comment by Jinjiang** [comment]
@bencodezen thanks for your information!

And btw let all the community know we are preparing the new v3 Chinese doc site here: https://github.com/vuejs/docs-next-zh-cn
Contribution welcome for everyone!

**Comment by Jinjiang** [comment]
Since the translation is done. I'd like to close this issue if you folks don't mind. 🙏
