### ISSUE TITLE
小疑惑

### ISSUE THREAD

**Issue by 5-seasons** [vuejs/cn.vuejs.org#1146]
![Screenshot_20210227_081959](https://user-images.githubusercontent.com/62876589/109369409-36587280-78d7-11eb-9096-458698605fb8.jpg)

教程2.x>基础>安装>对不同构建版本的解释>术语>UMD中，最后的括号中应该是vue.min.js－压缩的生产版本吧！

**Comment by Jinjiang** [comment]
Hi 这个问题建议直接到 https://github.com/vuejs/vuejs.org 问一下，因为其实这个不是翻译问题，是针对内容也就是原文的讨论。一旦这个问题在那边有结论或产生任何修改，中文版文档会及时从那边同步和跟进。谢谢

**Comment by 5-seasons** [comment]
好的。已经在 https://github.com/vuejs/vuejs.org 处提了issue

**Comment by Jinjiang** [comment]
https://github.com/vuejs/vuejs.org/issues/2777

感谢，帮你做个链接在这里

**Comment by Jinjiang** [comment]
@5-seasons 鉴于这个 issue 没有立即得到英文版的回复和处理，我建议先关掉这里的 issue 了，待英文版有结论之后，我们会通过定期的翻译同步把相应可能的更新带回中文版。感谢配合！
