### ISSUE TITLE
关于HTML特性的数据绑定问题

### ISSUE THREAD

**Issue by KingMario** [vuejs/cn.vuejs.org#119]
文档中有这样一句话：

> 注意在 Vue.js 指令和特殊特性内不能用插值

请问这里的 `和特殊特性` 指的是哪些特性？
多谢～～～

**Comment by yanxyz** [comment]
特殊特性是 vue.js 扩展的特性，比如 is。后面一句也说了：“不必担心，如果 Mustache 标签用错了地方 Vue.js 会给出警告。”。
