### ISSUE TITLE
amazing url, refresh forever

### ISSUE THREAD

**Issue by zhiyouth** [vuejs/cn.vuejs.org#1202]
https://v3.cn.vuejs.org/guide/render-function.html#%E6%B8%B2%E6%9F%93%E5%87%BD%E6%95%B0%E7%9A%84%E8%BF%94%E5%9B%9E%E5%80%BC

**Comment by Jinjiang** [comment]
@zhiyouth I didn't get your point. Could you please provide more information? Thanks.

**Comment by zhiyouth** [comment]
Click on this link, Then you will find the problem
Link: [vue3中文文档渲染函数的返回值](https://v3.cn.vuejs.org/guide/render-function.html#%E6%B8%B2%E6%9F%93%E5%87%BD%E6%95%B0%E7%9A%84%E8%BF%94%E5%9B%9E%E5%80%BC)

**Comment by wxsms** [comment]
> Click on this link, Then you will find the problem Link: [vue3中文文档渲染函数的返回值](https://v3.cn.vuejs.org/guide/render-function.html#%E6%B8%B2%E6%9F%93%E5%87%BD%E6%95%B0%E7%9A%84%E8%BF%94%E5%9B%9E%E5%80%BC)

I can't see any problem here. If you do meet any and prefer to solve them, it's better to provide more specify information, for example images/video/gif, alone with your os/browser type/version.
