### ISSUE TITLE
website error for cn.vuejs.org

### ISSUE THREAD

**Issue by lihugang** [vuejs/cn.vuejs.org#1217]
404 site not found
[cn.vuejs.org](https://cn.vuejs.org)
![cn vuejs org_](https://user-images.githubusercontent.com/94808542/182374206-4fc5ed67-a214-483e-a1af-1a045e7e40cf.png)

**Comment by lihugang** [comment]
location: Shanghai, China
ISP: telecom

**Comment by lihugang** [comment]
@yyx990803

**Comment by Jinjiang** [comment]
网站在升级🙏

**Comment by yyx990803** [comment]
It's back up!

**Comment by lihugang** [comment]
thanks
