### ISSUE TITLE
vue指令没有解释isFn选项的意义

### ISSUE THREAD

**Issue by youngwind** [vuejs/cn.vuejs.org#133]
文档中关于自定义指令的部分：https://vuejs.org.cn/guide/custom-directive.html
并没有提到isFn选项的意义。
但是我在看vue-touch的源码的时候看到了作者使用了这个选项，能把这个文档补充上吗？

https://github.com/vuejs/vue-touch/blob/master/vue-touch.js 
第22行

另外，我本身也不确定这个选项的意义。

**Comment by yanxyz** [comment]
isFn 的意思可查看 1.x 的源码。

**Comment by Jinjiang** [comment]
这里没有更多讨论的话我先关掉了，同时最新的 Vue 和文档已经是 2.0 了，可以继续保持关注
谢谢
