### ISSUE TITLE
添加关于computed的cache的说明

### ISSUE THREAD

**Issue by zyf0330** [vuejs/cn.vuejs.org#136]
文档的[计算属性](https://github.com/vuejs/cn.vuejs.org/blob/master/src/guide/computed.md)页面内，没有对cache的相关描述，而要在[计算属性的奥秘](http://cn.vuejs.org/guide/reactivity.html#计算属性的奥秘)才能看到，我认为这是不合适的。毕竟cache是computed本身的一个属性。

**Comment by Jinjiang** [comment]
你好，文档本身内容的修改意见需要同时在多国语言之间同步，且会先从英文开始比较好操作。建议您通过对英文版文档的讨论和提议来改善这一问题，那里也会得到更充分的讨论。
这里 issue 我先关掉了，希望可以理解
另外现在最新的文档已经是 2.0 了，相关的想法和问题可以基于 2.0 文档再讨论，同样希望可以从英文文档的仓库 issue 发起
谢谢
