### ISSUE TITLE
请问 Vue 2.0 的翻译是否可以合并进来？

### ISSUE THREAD

**Issue by dingyiming** [vuejs/cn.vuejs.org#140]
最近得到了尤大的推广，我们进行的 Vue 2.0 翻译工作有了很强的推动力，目前翻译基本完成，还在进行进一步的校对工作，不知道我们是否可以合并到`cn.vuejs.org` 中 ？
- 发布网址 ： http://vuefe.cn
- 翻译仓库与进度汇总 https://github.com/vuefe/vuejs.org 
- 翻译 issue https://github.com/vuefe/vuejs.org/issues
- Guide 翻译 issue https://github.com/vuefe/vuejs.org/issues/1
- API 翻译 issue https://github.com/vuefe/vuejs.org/issues/44
- Guide 翻译校对 https://github.com/vuefe/vuejs.org/issues/77
- 谢谢

**Comment by Jinjiang** [comment]
@yyx990803 我觉得可以考虑一下把 vuefe.cn 的翻译作为官方文档的一部分，同时把 1.x 的内容保留在一个目录或域名。
另外 vuex、router、ssr、awesome 的部分可以再讨论一下怎么处理 (现在这些内容还没有出现在英文的官网中，不知道你未来有没有放到一起的打算，另外 router 目前已经在 router.vuejs.org 有中文版了)

**Comment by yyx990803** [comment]
过段时间会把 v1 的中文文档移到 v1-cn.vuejs.org

到时候可以把你的仓库作为 cn.vuejs.org 的 2.0 分支。

**Comment by dingyiming** [comment]
@yyx990803 @Jinjiang 好的，太棒了，感谢。

接下来我们打算继续进行

- Vue 2.0 中文文档的校对
- 相关工具文档（如 Vuex ）的翻译

**Comment by dingyiming** [comment]
已经在做 `cn.vuejs.org`  `2.0` 分支准备 

- 当前地址 ： http://org.vuefe.cn/guide/
- 仓库分支 ： https://github.com/vuefe/vuejs.org/tree/2.0

**Comment by yyx990803** [comment]
@dingyiming 已经邀请你加入 vuejs organization - 加入后可以对 cn.vuejs.org 仓库获得 push 权限，可以创建一个 2.0 分支把当前仓库的内容推送上来，准备 ok 以后 ping 我做最后的部署 :)

**Comment by dingyiming** [comment]
@yyx990803 哦，抱歉，现在才看到，正好 @Jinjiang 提醒了我下，现在已经加入了，我们正在协商如何进行 vue 中文文档的推进。
