### ISSUE TITLE
搜索

### ISSUE THREAD

**Issue by yyx990803** [vuejs/cn.vuejs.org#146]
需要我去跟 algolia 那边沟通。

**Comment by yyx990803** [comment]
@maxiloc would you mind setting up a separate docsearch index for cn.vuejs.org? There are a LOT of Chinese Vue users and it'd be nice if they can have Chinese search results instead of English ;)

**Comment by maxiloc** [comment]
Yes sure I'll set it up as soon as I'll be next to a computer.

**Comment by maxiloc** [comment]
Here you go:
index_name: vuejs_cn2
api_key: 5638280abff9d207417bb03be05f0b25

Tell me if it's ok for you

By the way, we offer an analytics page which can help you understand what people are searching for.
You can for example see which request does not return any result. This can give you insights on where to improve the doc content 
if you want to have access to it. Just create an Algolia account and ping me. I'll give you access for the 3 vuejs index

Cheers

**Comment by yyx990803** [comment]
@maxiloc awesome, thank you so much for the consistent and fast support. I've signed up with my email address ([my github username] at [gmail]).

**Comment by maxiloc** [comment]
You should have access now.
Just go to the docsearch app of your account (see the screenshot above). and go to the analytics tab.

you have access to the following indices:
- vuejs
- vuejs_cn
- vuejs_jp
- vuejs_1
- vuejs_cn2


![image](https://cloud.githubusercontent.com/assets/1689007/20060953/f086ec8e-a4fd-11e6-82bd-848208dd6714.png)

**Comment by yyx990803** [comment]
@maxiloc thanks!
