### ISSUE TITLE
v1的中文翻译无法访问

### ISSUE THREAD

**Issue by n37r06u3** [vuejs/cn.vuejs.org#149]
http://cn.vuejs.org/

默认直接到v2了，点击v1就跳转到英文文档

**Comment by Jinjiang** [comment]
@yyx990803 我觉得可以把 1.x 的文档部署到类似 v1.cn.vuejs.org 的域名，然后把 2.0 中的旧文档链接指向这个域名

**Comment by Jinjiang** [comment]
同 #148

**Comment by tolerious** [comment]
我说的怎么1.0的访问不了了。

**Comment by yuu2lee4** [comment]
什么时候能修正呢 公司的后端表示看着费力

**Comment by Jinjiang** [comment]
我周末弄一下……

**Comment by Jinjiang** [comment]
https://vuejs.github.io/v1-cn.vuejs.org/
我看有个 v1-cn.vuejs.org 的空项目，就暂时把 v1 的内容部署到这里了，不过现在访问的时候很多资源路径有点问题，另外需要 @yyx990803 指向相应的域名

**Comment by Jinjiang** [comment]
http://v1-cn.vuejs.org/ 可以访问了

**Comment by yuu2lee4** [comment]
3q @Jinjiang
