### ISSUE TITLE
生命周期钩子表格中 destroy 名字错误

### ISSUE THREAD

**Issue by kid-wumeng** [vuejs/cn.vuejs.org#156]
[https://vuefe.cn/guide/instance.html](https://vuefe.cn/guide/instance.html)

![image](https://cloud.githubusercontent.com/assets/10629224/20329906/1a465f4e-abd6-11e6-8222-13d8bff4aa14.png)
)

destoryed -> destroyed
beforeDestory -> beforeDestroy

**Comment by dingyiming** [comment]
好的
