### ISSUE TITLE
關於树形视图 範例中使用了 ":model" 這樣的方法

### ISSUE THREAD

**Issue by imagine10255** [vuejs/cn.vuejs.org#157]
https://cn.vuejs.org/v2/examples/tree-view.html
树形视图 範例中使用了 ":model" 這樣的方法

可是我找不到官方說明文件哪個地方有寫到這個方法

關鍵字下 vuejs :model 也找不到 ＠＠

想請教這是甚麼意思呢 ?

![image](https://cloud.githubusercontent.com/assets/5771353/20354399/f63f724c-ac58-11e6-9757-6c8a471a8d72.png)

**Comment by yyx990803** [comment]
请仔细阅读文档：http://cn.vuejs.org/v2/guide/syntax.html#缩写

---

请注意，issue 是用来报 bug 的，不是用来提问的。报 bug 时，请仔细阅读 [开 issue 须知](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines)，确保有完整的重现步骤。不符合要求的 issue 会被直接关闭。

**Comment by imagine10255** [comment]
抱歉, 知道了＠＠
