### ISSUE TITLE
请问可有epub或者Pdf等电子书格式下载？

### ISSUE THREAD

**Issue by tenlee2012** [vuejs/cn.vuejs.org#168]
这样就可以离线阅读学习了

**Comment by Jinjiang** [comment]
暂时没有这方面的打算，而且 Vue 其实还是在保持迭代更新的，建议以网站上最新的文档为参考
如果自己有类似的需求，也可以试试用 gitbook 之类的工具自行生成，这里不做展开了
谢谢
