### ISSUE TITLE
网页在Chrome浏览器顶部透明

### ISSUE THREAD

**Issue by zxhycxq** [vuejs/cn.vuejs.org#171]
360浏览器正常，chrome背景透明了。
`#header `部分

![image](https://cloud.githubusercontent.com/assets/11674203/20692270/c2a30b84-b611-11e6-91d7-14459ec46bd9.png)

**Comment by ziolau** [comment]
查了一下，代码里面有
```
@media screen and (min-width: 1590px)
#header {
    background-color: rgba(255,255,255,0.4);
}
```
再者，众所周知，360浏览器是双核浏览器，估计你打开的是ie内核模式的，不支持rgba。

**Comment by zxhycxq** [comment]
@ziolau  360是正常的，用的是极速模式。谷歌不对，因为多了（min-width: 1360px）。不知道为何把断点设置为1360 ，改为1366之后就没事了。（我用的笔记本）

**Comment by ziolau** [comment]
我的是 1590px 以下的都是白色不透明。

**Comment by yyx990803** [comment]
故意这么设计的。窄屏时候不透明为的是不干扰菜单。
