### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by anhulife** [vuejs/cn.vuejs.org#174]
[Vue 实例](https://cn.vuejs.org/v2/guide/instance.html)章节中最下方的生命周期钩子对比图中，`destroy`被拼写成了 `destory`。

![生命周期钩子](https://cloud.githubusercontent.com/assets/12537013/17702060/f847b38a-63fe-11e6-9c29-38e58d46f036.png)

**Comment by Jinjiang** [comment]
这个图应该是放错地方了，现在已经去掉了，谢谢反馈
