### ISSUE TITLE
“介绍”页 代码少一个闭合标签

### ISSUE THREAD

**Issue by zxhycxq** [vuejs/cn.vuejs.org#191]
介绍页面 http://cn.vuejs.org/v2/guide/ 
官网上面少了个`</script>` 闭合标签（第一张图），但是点击页面底部的“发现错误或想贡献文档？ 在 Github 编辑此页!”，却发现GitHub上面相应的[index.md](https://github.com/vuejs/cn.vuejs.org/blob/master/src/v2/guide/index.md)文档是正确的（第二张图）。
是格式没有转换正确还是？另外两者的内容似乎不太相同（截图中代码的前一段最后一句）。

> ![image](https://cloud.githubusercontent.com/assets/11674203/21165057/ceb17c04-c1d7-11e6-9429-851d2398f196.png)

> ![image](https://cloud.githubusercontent.com/assets/11674203/21165067/e06743fc-c1d7-11e6-95c9-a5b7c5ee8cc2.png)

**Comment by Jinjiang** [comment]
刚有个 pr 已经修复了，晚些时候我们更新发布上去就好了
