### ISSUE TITLE
最近搜索结果都变成英文了

### ISSUE THREAD

**Issue by u3u** [vuejs/cn.vuejs.org#195]
![search](http://p1.bqimg.com/549484/1f1819234f862758.png)
跳转也直接跳到 http://vuejs.org/ 之前是正常的QAQ

**Comment by Jinjiang** [comment]
@yyx990803 求助 - -

**Comment by kazupon** [comment]
@Jinjiang 
 it might be of your help.
https://github.com/vuejs/vuejs.org/issues/575#issuecomment-262624969

**Comment by Jinjiang** [comment]
@kazupon Thank you. I will update it soon :-)

**Comment by yyx990803** [comment]
@maxiloc - we accidentally overwritten the cn site with the API key for the English version, but after reverting to the [key for the Chinese index](https://github.com/vuejs/cn.vuejs.org/blob/master/themes/vue/layout/layout.ejs#L79-L80) the queries are now always returning empty results. Any ideas?

**Comment by dingyiming** [comment]
我的错，之前从 vuejs.org 获取更新到 vuefe 改中文后，没有更改中文搜索，真抱歉

**Comment by maxiloc** [comment]
@yyx990803 The configuration of the crawler was still the old one so the v2 version tag did not exist. Just fixed it, should be good now.

**Comment by Jinjiang** [comment]
@maxiloc It works! Thank you very much :-)

**Comment by u3u** [comment]
@Jinjiang 谢谢 现在恢复正常了 大家辛苦了！
对了 我还有一个建议哦 我发现搜索接口返回的 `url` 是绝对地址 我认为应该改成相对路径
这么做有几个好处 例如这次出现的搜索结果变成英文的问题 如果 `url` 是相对的 那至少影响不大
还是可以跳转过去查看 还有一个就是我发现 http://cn.vuejs.org 服务器是放在国外的 有时候访问慢
就拉了一下仓库在本地部署一个 `gh-pages` 服务 这样会很方便 访问速度也很快 即使没有网络的时候也能查看 不过因为搜索接口返回的 `url` 写死了域名 这样的话在本地浏览也会跳转到 http://cn.vuejs.org

``` json
{
  "hierarchy": {
    "lvl2": "全局 API", 
    "lvl3": null, 
    "lvl0": "API", 
    "lvl1": null, 
    "lvl6": null, 
    "lvl4": null, 
    "lvl5": null
  }, 
  "url": "http://cn.vuejs.org/v2/api/#全局-API", 
  "content": null, 
  "anchor": "全局-API", 
  "objectID": "914724202", 
  "_highlightResult": {
    "hierarchy": {
      "lvl2": {
        "value": "全局 <span class=\"algolia-docsearch-suggestion--highlight\">A</span>PI", 
        "matchLevel": "full", 
        "fullyHighlighted": false, 
        "matchedWords": [
          "a"
        ]
      }, 
      "lvl0": {
        "value": "<span class=\"algolia-docsearch-suggestion--highlight\">A</span>PI", 
        "matchLevel": "full", 
        "fullyHighlighted": false, 
        "matchedWords": [
          "a"
        ]
      }
    }, 
    "hierarchy_camel": {
      "lvl2": {
        "value": "全局 <span class=\"algolia-docsearch-suggestion--highlight\">A</span>PI", 
        "matchLevel": "full", 
        "fullyHighlighted": false, 
        "matchedWords": [
          "a"
        ]
      }, 
      "lvl0": {
        "value": "<span class=\"algolia-docsearch-suggestion--highlight\">A</span>PI", 
        "matchLevel": "full", 
        "fullyHighlighted": false, 
        "matchedWords": [
          "a"
        ]
      }
    }
  }
}
```

**Comment by Jinjiang** [comment]
这个搜索服务是第三方提供的，本身有一定的局限性，目前这样的状态我觉得是可接受的
感谢你的建议

**Comment by wuliupo** [comment]
@u3u I have fixed this url issue on my localhost: replace the ajax content.
修改第三方服务返回的字符串中的url
