### ISSUE TITLE
页面搜索请求返回了结果，但是页面上没有显示？

### ISSUE THREAD

**Issue by HenryYong** [vuejs/cn.vuejs.org#196]
![image](https://cloud.githubusercontent.com/assets/7967105/21303647/ac1145ae-c5fa-11e6-98b8-c064e504a369.png)

**Comment by Jinjiang** [comment]
我们今天正在调试这块 #195 稍安勿躁：）
这个 issue 我先 close 了，更多问题可以在 #195 继续
