### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by yyx990803** [vuejs/cn.vuejs.org#197]
@dingyiming 最近已经两次错误的把 cn.vuejs.org force push 到 vuejs.org 的主仓库了，小心一点啊

**Comment by dingyiming** [comment]
真是抱歉，我查看下在什么时候做了这么糟糕的事情

**Comment by dingyiming** [comment]
我是把推送了新分支到 vuejs.org 吗？ 我这边查不到记录，是分支已经删除了吗？对不起，给大家添麻烦了。

**Comment by yyx990803** [comment]
覆盖了 vuejs.org 的 master...
看看是不是 git remote origin 配错了

**Comment by dingyiming** [comment]
从 github 的记录上看到有提交次数记录，本地有个三个源，可能是没注意的时候，推错了源，我把本地的vuejs.org源删除，一般主要是用于 获取 vuejs.org 的更新，未曾想出乎意料地反推回去了，真是抱歉，后面还得多小心点。

![image](https://cloud.githubusercontent.com/assets/12537013/21442527/4875e0f4-c8d9-11e6-9a3e-6d156bdf0266.png)

![image](https://cloud.githubusercontent.com/assets/12537013/21442545/6c8918c6-c8d9-11e6-8b00-5167d880ecdb.png)
