### ISSUE TITLE
需要更新中文文档了吧

### ISSUE THREAD

**Issue by LeslieYQ** [vuejs/cn.vuejs.org#2]
1.0 版本出来了，感觉中文这边还是0.12的文档。

例如 repeat貌似被去除了，很多人都不知道呢。

**Comment by BuptStEve** [comment]
https://github.com/vuejs/cn.vuejs.org/issues/1

已翻译完，等尤大大校正？

**Comment by Jinjiang** [comment]
刚翻译完，现在在校对中，稍后会更新
