### ISSUE TITLE
点击左侧导航中“段落标签”，当包含中文时在safari10.0.2无效。

### ISSUE THREAD

**Issue by YuanChenmang** [vuejs/cn.vuejs.org#200]
例如：
教程--》安装中找到“CDN”段落和“CSP环境”，点击“CDN”页面会拉到CDN段落，而点击“CSP环境”时页面在safari上没反应，在chrome上可以。

**Comment by Jinjiang** [comment]
定位了一下问题，Safari 下 `document.querySelector('#中文')` 是正常的，但是写一个 `<a href="#中文">`，然后 `document.querySelector(a.hash)` 就找不到了，因为这个 hash 值 `"#%E4%B8%AD%E6%96%87"` 被转码过了，转码过之后 Safari 自己不认识了……

我试了试最新版的 smoothScroll 不会报错，可以正常跳转，但是动画没有了 (起码比现在跳不过去要好)

@yyx990803 我们要不要升级一下 smoothScroll 的版本？Safari 的这个问题我估计未来会修复，不用太纠结

p.s. smoothScroll 那边我同时也开了个 issue https://github.com/cferdinandi/smooth-scroll/issues/305

**Comment by yyx990803** [comment]
升级下呗。升级以后在其他浏览器下应该还是有动画的吧？

**Comment by Jinjiang** [comment]
升级了，但似乎还是有点问题…… 明天我再看看
