### ISSUE TITLE
example1.items.splice(indexOfItem, 1, newValue) 并不能达到 vm.items[indexOfItem] = newValue 效果

### ISSUE THREAD

**Issue by liqianglai** [vuejs/cn.vuejs.org#206]
注意事项
由于 JavaScript 的限制， Vue 不能检测以下变动的数组：
1. 当你利用索引直接设置一个项时，例如： vm.items[indexOfItem] = newValue
2. 当你修改数组的长度时，例如： vm.items.length = newLength
为了避免第一种情况，以下两种方式将达到像 vm.items[indexOfItem] = newValue 的效果， 同时也将触发状态更新：
```
// Vue.set
Vue.set(example1.items, indexOfItem, newValue)
```
```
// Array.prototype.splice 
// 经测试当 indexOfItem 超出数组长度时，该方法不能达到 vm.items[indexOfItem] = newValue 这个效果
// 相当于 example1.items.push(newValue)
example1.items.splice(indexOfItem, 1, newValue)
```

**Comment by Jinjiang** [comment]
Vue 本身的问题请直接在 vue 主仓库提问吧，这里只做中文翻译和相关讨论
请见谅
