### ISSUE TITLE
本地编译，API页面只有一部分内容

### ISSUE THREAD

**Issue by wuliupo** [vuejs/cn.vuejs.org#225]
本地编译，API 页面只有一部分内容。

重现步骤（Windows 10，Mac 10）
```
git clone https://github.com/vuejs/cn.vuejs.org
cd cn.vuejs.org
npm install
hexo server
```
打开：http://localhost:4000/v2/api/

![api](https://cloud.githubusercontent.com/assets/1187809/22242903/23566c94-e260-11e6-8762-47d36c11a354.png)
![source](https://cloud.githubusercontent.com/assets/1187809/22242904/2498f64e-e260-11e6-8471-d42f99ed9e3e.png)

**Comment by Jinjiang** [comment]
是 Hexo hot reload 的一个已知问题，hexo generate 然后放在本地静态服务器上是正常的
暂时没有解决办法，而且需要 Hexo 做修复，这里先关掉了
谢谢理解

**Comment by wuliupo** [comment]
Thank you~
