### ISSUE TITLE
计算属性中不恰当的例子

### ISSUE THREAD

**Issue by andrew-qiu** [vuejs/cn.vuejs.org#229]
在计算缓存 vs Method一节中，使用了Date.now作为计算缓存的例子：
computed: {
  now: function () {
    return Date.now()
  }
}
但是，实际运行后会发现Date.now在computed和methods中的调用结果是完全相同的（因为时间相隔较短），不能说明问题！

因此，建议把Date.now改为Math.random，这样就能看出computed和methods两种调用的区别啦。

**Comment by Jinjiang** [comment]
这里只讨论翻译问题，原文合理性讨论建议在原文的 repo 里开 issue 讨论：
https://github.com/vuejs/vuejs.org/issues/
原版接受并修改了，我们这边再同步更新
感谢理解
