### ISSUE TITLE
关于currencyValidator

### ISSUE THREAD

**Issue by nicky-lau** [vuejs/cn.vuejs.org#232]
在组件的"使用自定义事件的表单输入组件"章节中的demo使用了`currencyValidator.format`这个方法，但是文档中并未提及这个方法的定义，全文搜索'currencyValidator'虽然可以看到有这个方法的说明文档，但是指向的gist，对于不能翻墙的国内苦逼感觉很胸闷。

**Comment by nicky-lau** [comment]
最后在fiddle中找到了，[currency-validator.js](https://cdn.rawgit.com/chrisvfritz/5f0a639590d6e648933416f90ba7ae4e/raw/98739fb8ac6779cb2da11aaa9ab6032e52f3be00/currency-validator.js),同时还显示用到了[accounting.min.js](https://cdnjs.cloudflare.com/ajax/libs/accounting.js/0.4.1/accounting.min.js)

**Comment by Jinjiang** [comment]
这里仅解决语言障碍的问题 (英翻中)，物理障碍我们的力量太渺小了，建议还是开发者自己想办法吧……
希望理解
