### ISSUE TITLE
为什么我不能访问这个https://cn.vuejs.org这个安全协议地址？但是改为http却可以？

### ISSUE THREAD

**Issue by piaohan** [vuejs/cn.vuejs.org#252]
为什么我不能访问这个https://cn.vuejs.org这个安全协议地址？但是改为http却可以？而楼主README.md让访问的是HTTPS。请问服务器是否配置正确或者安全协议组织签名到期？

**Comment by Jinjiang** [comment]
我这里 https 访问正常，怀疑你本地的网络被拦截了
