### ISSUE TITLE
从 Vue 1.x 迁移->Slots->重命名的Slot中有错字

### ISSUE THREAD

**Issue by nkdanfer** [vuejs/cn.vuejs.org#271]
同一模板中的重名 <slot> 已经弃用。当一个 slot 已经被渲染过了，那么就不能在同一模板其它地方被再次渲染了。如果要在不同位置渲染同一内容，可一用prop来传递。 

这里应该是“可以”而不是“可一”。

**Comment by Jinjiang** [comment]
源码已修复，稍后发布，谢谢
