### ISSUE TITLE
单向数据流中的例子有误

### ISSUE THREAD

**Issue by RoamIn** [vuejs/cn.vuejs.org#286]
原文如下：
> 1. 定义一个局部变量，并用 prop 的值初始化它：
```
props: ['initialCounter'],
data: function () {
  return { counter: this.initialCounter }
}
```
实际上这样修改组件的 counter，并不适用于对象、数组。如果 initialCounter 是对象、数组，如何避免影响父级的数据呢？并且改变props里面的属性并不会给予警告。

**Comment by Lesty612** [comment]
首先，这个问题提在这里应该不太合适。
然后，作者应该不是很反对`这种方式`(传对象进props)，这可以作为简易的父子组件双向通信的解决方案。
最后，如果你想避免影响父级数据，那建议你可以尝试下对象的深度拷贝，知乎链接[javascript中的深拷贝和浅拷贝？](https://www.zhihu.com/question/23031215)
