### ISSUE TITLE
地址替换

### ISSUE THREAD

**Issue by aimuz** [vuejs/cn.vuejs.org#298]
能不能把大量js文件地址替换为本地。经过镜像https://cn.vuejs.org/后发现，//cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.min.js 拖慢了速度

**Comment by aimuz** [comment]
镜像后的地址为 vuejs.boiko.cn

**Comment by Jinjiang** [comment]
cn.vuejs.org 实测也是走了 cloudflare 的 cdn 结点，网络状况和 cdnjs 这个域名是相当的，暂不必更换了
不过还是谢谢你的支持和建议
