### ISSUE TITLE
我的 review 备忘

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/cn.vuejs.org#3]
因为改动和建议都是很小的一部分，整体发和单个发 MR 都不太合适，这里直接备忘吧，大家认同之后谁更新都不重要了：

翻译建议：

- `themes/vue/layout/index.ejs`
    - [ ] L121：多了一个字母 B
- `guide/index.md`
    - [ ] L155：综合 -> 现在都放到一起
    - [ ] L226：我知道你现在有许多疑问——继续阅读，在后面的教程将一一解答 -> 我知道你现在还有很多疑问——请继续读下去，我们在后面的教程里都进行了阐述。 *(主语前后不一致，不能省略)*

术语的几种译法提议：

- [ ] reactive：可反应的 | 主动响应 | 自驱动 (坦白讲我自己觉得 vue.js 是数据驱动的，这里描述的挺准确的，但不完全算 reactive 吧？也许是我对 reactive 这个词的理解不对……)
- [ ] computed property：经过计算的属性 | 可推导的属性 (译作“计算属性”时这里的直觉是“计算”是动词)

还在陆续看，看到之后就更新到这条 issue，不另外开了

**Comment by Jinjiang** [comment]
翻译建议：

- `guide/installation.md`
    - L15：`Vue` 被注册为一个全局变量。 -> `Vue` 会被注册为一个全局变量。
    - L18：包含丰富的注释和调试信息。 -> 包含完整的警告和调试模式 *(没有标点)*
    - L33：Vue.js 能很好地与 CommonJS 兼容模块打包器如……配合使用。 -> NPM 能很好地和诸如……的 CommonJS 模块打包器配合使用。
    - L38：最新稳定版本 + CSP 兼容版本 -> 最新稳定 CSP 兼容版本

**Comment by yanxyz** [comment]
我知道你现在有许多疑问——继续阅读，在后面的教程将一一解答 -> 我知道你现在还有很多疑问——请继续读下去，我们在后面的教程里都进行了阐述。 (主语前后不一致，不能省略)
是说，前面是我，后面是我们？

computed property 这个在文档中是术语，"经过计算的属性 | 可推导的属性" ，偶尔用一下可以，用作术语就不合适了。是翻译为“计算”还是“推导”？我是最直接的翻译。有一个参考例子 computed price，是财经方面的术语。

**Comment by Jinjiang** [comment]
中间的 继续阅读 是祈使句，后面的主语应该是第一人称，最好写明

**Comment by Jinjiang** [comment]
> computed property 这个在文档中是术语，"经过计算的属性 | 可推导的属性" ，偶尔用一下可以，用作术语就不合适了。是翻译为“计算”还是“推导”？我是最直接的翻译。有一个参考例子 computed price，是财经方面的术语。

现在提取术语的主要意义在于统一译法，理解起来最直接成本最低误解最少为妥，我觉得计算这种译法不太直接。你提出的参考例子，我的感觉：1 这不是一个前端知识领域可对比的东西；2 已有被公认的术语也未必是最合理的译法，有很多历史因素，比如计算机里的“遍历”、“正则”其实并不是很直观的译法，有点扯远了…… 总之如果大家有觉得更好的译法，我希望不是“计算属性”

还有一个建议就是在不直观但没有更好译法的时候选择直译，然后在旁边 (或仅第一次出现时) 加英文注释

**Comment by yanxyz** [comment]
computed property 已经是最直译了哦。

**Comment by Jinjiang** [comment]
是的，我的意思是计算属性是直译，但中文阅读起来不是很通顺，希望探讨一下有没有更好的译法，这个小问题不然 @yyx990803 也来拿个主意吧，我就不纠结了……

**Comment by yyx990803** [comment]
就叫 `计算属性` 吧... 其实术语只要统一了以后用久了就习惯了。

**Comment by yanxyz** [comment]
代码注释也是翻译了。有没翻译的指出来看一下。

**Comment by yanxyz** [comment]
> reactive：可反应的 | 主动响应 | 自驱动 (坦白讲我自己觉得 vue.js 是数据驱动的，这里描述的挺准确的，但不完全算 reactive 吧？也许是我对 reactive 这个词的理解不对……

在看到 reactive 时，我常常想到 Responsive web design，这个大家基本统一为 “响应式网页设计”。reactive，responsive 都可以翻译为“响应”。在 vue.js 中 reactive 的含义是响应（数据的变化），明白这点就明白了。

我举 computed price 这个例子，虽然不是技术领域的术语，但是都是翻译，不是没有参考意义。计算属性，这里计算不应看作是动词，这也算汉语的一个特点。

多说一句，你会发现我一般省略了主语，数量词。不然会看到满篇的 ”你“，”一个“等。

**Comment by Jinjiang** [comment]
- `overview.md`
    - [ ] L7: Vue.js 的目标是尽可能简单地实现…… -> Vue.js 的目标是通过尽可能简单的 API 实现……
    - [ ] L9: Vue.js 也能完美地驱动单页应用。 -> Vue.js 也能完美地驱动复杂的单页应用。
    - [ ] L15: 于是应用的多数逻辑现在变为直接修改数据，不必与 DOM 更新搅在一起。-> 这样我们应用中的逻辑就几乎都是直接修改数据了，不必与 DOM 更新搅在一起。
    - [ ] L56: 数据与 DOM 现在链接起来，是**响应的**。我们如何知道？ -> 数据与 DOM 现在是链接起来的，并且一切都是**响应的**。如何确认这件事呢？
    - [ ] L56: 你将看到上例相应地更新。-> 你将看到上例相应的更新。
    - [ ] L91: 并且可能你已经猜到，它们应用特别响应的行为到 DOM 上。-> 可能你已经猜到了，它们在已经渲染好的 DOM 上应用了特殊的响应行为。
    - [ ] L91: 你将看到出现 "Hello!" 消息。-> 你会发现 "Hello!" 消失了。
    - [ ] L93: 可以在 Vue 插入/删除元素时自动地应用过渡效果。-> 可以在 Vue 插入/删除元素时自动应用过渡效果。
    - [ ] L99: 因为它是抽象的，故我们可以用小、独立且一般是复用的组件来构建大型应用。-> 因为它抽象了我们由独立可复用的小组件构建大型应用的方式。
    - [ ] L115: 定义在[Web 组件规范](http://www.w3.org/wiki/WebComponents/)中。实际上 Vue.js 的组件的语法参考了规范。 -> 它是 [Web 组件规范](http://www.w3.org/wiki/WebComponents/)的一部分。实际上 Vue.js 的组件语法参考了该规范。
    - [ ] L117: 在需要时 -> 必要时
    - [ ] L121: 可以与 Vue.js 一起构成一个差不多的“框架”系统。-> 它们和 Vue.js 一起构成了一个更加“框架”性的系统。

代码示例中注释似乎是翻译了，但是文字内容没翻译，比如：

`guide/index.md`

```
message: 'Hello Vue.js!'
...
{ text: 'Learn JavaScript' },
{ text: 'Learn Vue.js' },
{ text: 'Build Something Awesome' }
...
<button v-on:click="reverseMessage">Reverse Message</button>
...
{ text: 'Add some todos' }
```

`guide/overview.md`

```
<span v-if="greeting">Hello!</span>
```

不一一列举了，基本都属于示例的语境内容

**Comment by yyx990803** [comment]
代码示例里面就只翻译注释就可以了，内容就不要翻了。我觉得勾股的这些改动对于语言的通顺是有帮助的，你直接开个 PR 吧

**Comment by Jinjiang** [comment]
我主要是纠结如果这几条其中一条不合适，这个 PR 不太好进展下去了，大家接收的，在 checkbox 上打个勾，我再更新也不迟

**Comment by yyx990803** [comment]
`overview.md`

我觉得 ok 的都打了钩。另外：

- L56: 可以译作『并且 DOM 会自动响应数据的变化。』有时候并不一定要拘泥于原句的结构，意思表达得清楚就好。
- L91: 并且如你所想象的，它们会对绑定的目标元素添加响应式的特殊行为。
- L99: 因为它提供了一种抽象，让我们可以用独立可复用的小组件来构建大型应用。

**Comment by yyx990803** [comment]
@yanxyz 的翻译整体上意思表达得还是很准确的，就是一些地方可能过于追求 "terse"，读上去有一些冷冰冰的感觉。可以适当的保留一些助词让语句更柔和一些。

**Comment by yanxyz** [comment]
overview.md

> 你将看到上例相应地更新。-> 你将看到上例相应的更新。

这里我用 ”地“，是把”更新“当作动词，不过现在”地“，”的“ 人们不怎么区分了。当然如果把 ”更新“ 看作名词，那是要用 ”的“。

我的汉语表达能力还是不大好。大家提出来也有助于我发现问题。

建议按文件来，讨论通过后便修正它。如果都积到后面到时也是不小的量。如果是错别字直接改过来就好了。

对于代码，我只翻译了注释，其它的地方我觉得还是不动为好。

**Comment by yanxyz** [comment]
@yyx990803  边栏标题翻译，我是在 theme/partials/sidebar.ejs 加了一行代码实现的。看旧文档是在页面上加了一个全局变量 window.PAGE_TYPE，通过它实现的。不过我没搞清楚它是怎么变成中文的。

**Comment by LeslieYQ** [comment]
列表渲染---track-by "$index" 这里。 我觉得 “如果没有唯一的键供追踪” 是不是去掉 “的” 直接使用 “唯一键” 顺溜一点。

**Comment by yanxyz** [comment]
@LeslieYQ  这个嘛，见仁见智。

**Comment by Jinjiang** [comment]
- `guide/instance.md`
  - [ ] L9: 每个 Vue.js 应用都是由 `Vue` 构造器创建的**根 Vue 实例**引导：> 每个 Vue.js 应用的第一步都是通过构造函数 `Vue` 创建一个 **Vue 的根实例**：
  - [ ] L17: 一个 Vue 实例不过是一个 [MVVM 模式](https://en.wikipedia.org/wiki/Model_View_ViewModel) 定义的 **ViewModel** ，因而你会看到变量名 `vm` 遍及文档。 > 一个 Vue 实例其实是一个 **ViewModel**，这个词来自 [MVVM 模式](https://en.wikipedia.org/wiki/Model_View_ViewModel)，因而 `vm` 这个变量名会遍及文档。
  - [ ] L28: 所有的 `MyComponent` 实例都将以预定义的扩展选项被创建
  - [ ] L32: 所有的 Vue.js 组件其实都是被扩展的 Vue 实例。
  - [ ] L36: 每个 Vue 实例都会**代理**其 `data` 对象里所有的属性：
  - [ ] L57: 这些属性与方法都有前缀 `$`
  - [ ] L94: Vue 实例

译法统一建议

- constructor 构造函数
- lifecycle callbacks 生命周期回调

**Comment by yyx990803** [comment]
L17 - 一个 Vue 实例其实正是一个 MVVM 模式中所描述的 ViewModel - 因此在文档中经常会使用 `vm` 这个变量名。

同意关于 constructor 和 lifecycle callbacks 的术语统一。

**Comment by yanxyz** [comment]
L9，我觉得还是直译好，bootstrap 我想改成 “启动”。 api/index.md 里面也有这么一句。“第一步” 可能会带来歧义，我的应用第一步可能是干其它的事，严格的说，只有 vue 的第一步是这样。

L28, L32 这两个被字句，建议去掉“被”。见参考：
https://zh.wikipedia.org/wiki/%E8%A2%AB%E5%AD%97%E5%8F%A5
英语的被动词不应一律加上“被”。实际上你会发现我很少加上 “被”。

constructor 我是统一翻译为“构造器”，如果要改会有很多的地方要改。以前，我是译为“构造函数”，因为 JS 没有 class 的概念，现在有了——尽管目前还只是语法糖。在其它语言里，constructor 大都是译为 “构造器”，所以我选择了这个译法。

lifecycle hooks 你打算怎么译？hooks 我是统一为“钩子”，callbacks 统一为“回调”（不是回调函数）。

提个建议，如果是添字建议放到括号内，这样一眼就能看明白，省得要翻看原文。

**Comment by Jinjiang** [comment]
- `guide/syntax.md`
    - [ ] L7: Vue.js 的模板是基于 DOM 实现的。这意味着所有的 Vue.js 模板都是可解析的有效的 HTML，且通过一些特殊的特性做了增强。
    - [ ] L21: 你也可以只处理一次插值，今后的数据变化就不会再引起插值更新了：
    - [ ] L27: 原始的 HTML
    - [ ] L35: 其内容会以为纯 HTML 格式插入
    - [ ] L51: 一段绑定表达式由一个简单的 JavaScript 表达式和可选的一个或多个过滤器构成。
    - [ ] L55: JavaScript表达式 -> JavaScript 表达式
    - [ ] L71: 可改用三元表达式
    - [ ] L83: “管输” -> “传输”
    - [ ] L103: 指令的职责就是当其表达式的值改变时把某些特殊的行为反应到 DOM 上。
    - [ ] L113: 有些指令可以在其名称后面带一个“参数”，并且以一个冒号将其隔开。
    - [ ] L131: 表明其所在的指令应该以某些特殊的方式被绑定
    - [ ] L141: 当你使用 Vue.js 在现成的标签上处理动态行为时这非常好用，但是当你反复高频率的使用指令时，这又会显得笨重。
    - [ ] L141: 因此Vue.js 为两个最常用的指令…… -> 因此 Vue.js 为两个最常用的指令……
    - [ ] L163: 所有支持 Vue.js 的浏览器中 -> 所有 Vue.js 支持的浏览器中
    - [ ] L163: 不过随着一步步学习的深入，你会庆幸拥有它们。

译法统一建议：

- partials 粒子|粒子模板
- literal 字面量

**Comment by yyx990803** [comment]
partial 不是 particle 啊... partial 因为会在 API 中出现，建议第一次出现时加个括号 `parial (模板片段)`，之后都统一用原文 `partial`。

**Comment by Jinjiang** [comment]
L9 L28 L32 我觉得改进后的念起来更通顺自然，我也不是一律都加，是觉得这些地方不通顺

> lifecycle hooks 你打算怎么译？hooks 我是统一为“钩子”，callbacks 统一为“回调”（注意不是“回调函数”）。

无异议，“lifecycle hooks”我会直译为“生命周期钩子”

**Comment by yanxyz** [comment]
中英文之间的空格，之前没有检查到，直接改过来就好了。

 L51: 一段绑定表达式，“一段”是不是“一个”呀？

 L83:  我是专门将 pipe 直译为 “管输”，单独译为 “传输” 体现不出来。要不附上英文？

 L103： 反应到 DOM 上，“反应” 感觉用 “应用” 较好。

L113: 并且以一个冒号将其隔开。这里“其” 与前面的“其”混淆，建议改为“参数”。

**Comment by Jinjiang** [comment]
- `guide/computed.md`
    - [ ] L64: 你可以像绑定普通属性一样在模板中绑定计算属性。
    - [ ] L64: 因此当 `vm.a` 发生改变时，依赖于 `vm.b` 的绑定也会更新
    - [ ] L64: 计算属性的读取器是干净无副作用的，因此也是易于测试和理解的。
    - [ ] L68: 当你希望基于一些数据改变另一些数据时，最好试一试 `$watch`——尤其是有 AngularJS 背景的同学。而更好的选择通常是计算属性而不是命令式的 `$watch` 回调。
    - [ ] L133: 存储器会被调用，`vm.firstName` 和 `vm.lastName` 也会有相应更新。
    - [ ] L135: 关于计算属性背后的原理和技术细节详见响应系统介绍中的[具体章节](reactivity.html#Inside_Computed_Properties)。

译法统一建议

- getter 读取器
- setter 存储器

**Comment by Jinjiang** [comment]
`guide/syntax.md`

> L51: 一段绑定表达式，“一段”是不是“一个”呀？

我这里用了一段这个，因为我觉得刻意和后面的 JavaScript 表达式区分开量级，它们之间有包含关系但都叫表达式，在不影响整体理解的没有歧义的前提下我用了一个不一样的词

> L83: 我是专门将 pipe 直译为 “管输”，单独译为 “传输” 体现不出来。要不附上英文？

可以

> L103： 反应到 DOM 上，“反应” 感觉用 “应用” 较好。

没问题，我改成应用

> L113: 并且以一个冒号将其隔开。这里“其” 与前面的“其”混淆，建议改为“参数”。

那直接改成“中间放一个冒号隔开”如何？

**Comment by Jinjiang** [comment]
突发奇想 kebab-case 翻译成比较本土特点的“串糖葫芦式”怎么样？

**Comment by Jinjiang** [comment]
- `guide/conditional.md`
    - [ ] L33: 此时我们可以把一个 `<template>` 元素当做包装元素，并在上面使用 `v-if`。
    - [ ] L45: 另一个根据条件展示元素的选项是 `v-show` 指令。
    - [ ] L51: `v-show` 只会简单切换该元素 CSS 中的 `display` 属性。
    - [ ] L72: 因为它会确保条件块在开关期间，内部事件监听器和子组件的合理销毁和重建
    - [ ] L74: 原文“编译会被缓存起来”少了括号

译法统一建议

- toggle -> 开关
- listener -> 监听器 (handler -> 处理器)
- lazy -> 懒 (如懒加载)，原文“`v-if` 也是**懒**的”足矣

**Comment by yanxyz** [comment]
kebab-case 实际上我直译为 “肉串”，不过最后选择不译，是因为翻译后会损失掉一层意思。camelCase, PascalCase, kebab-case 这几个词放一块就可以看出它们本身还是范例。

getter/setter 我统一没译。要改会有许多地方要改。

toggle 我一般译为切换，切入切出。

**Comment by yyx990803** [comment]
getter / setter 建议不翻译。
lazy -> 惰性好一点吧，懒单独一个字总觉得怪怪的 -.-
toggle ->  叫切换比较自然一些。

**Comment by Jinjiang** [comment]
收到，上面其它修改建议大家没异议的我先默认进行提交发 PR

**Comment by yyx990803** [comment]
好~
另外 kebab-case 还是明确一点，翻成『短横分隔命名』吧...

**Comment by Jinjiang** [comment]
- `guide/list.md`
    - [ ] L9: 这个指令会使用形为 `item in items` 的特殊语法，其中 `items` 是数据源数组，而 `item` 是当前遍历到的数组元素的**别名**：
    - [ ] L109: 另外，你可以为索引（如果 `v-for` 的目标是对象而不是数组，则是该对象的键名）指定一个别名：
    - [ ] L134: Vue.js 包装了一套观察数组突变的方法，所以它们可以触发视图的更新。这些包装好的方法是：(英文中的“an ... methods”和“The ... methods”单复数是不是有问题？)
    - [ ] L156: 因而在两个有大量重叠元素的数组间替换的执行效率是非常高的
    - [ ] L160: 有时你需要把数组替换为一组全新的对象（例如通过调用 API 创建的一组对象）
    - [ ] L160: 通过数据对象的特征 -> 通过数据对象的*标识*
    - [ ] L185: 原位更新模式 -> *原地*更新模式
    - [ ] L185: 数据数组 -> 源数组
    - [ ] L191: Vue.js **不能**检测到下面数组*的*变化：
    - [ ] L205: 因此，不必这样： ... 只用这样： -> 因此与其这样： ... 不妨这样：
    - [ ] L275: 在遍历对象时，是按 `Object.keys()` 的结果遍历 -> 对象的遍历顺序基于 `Object.keys()` 的值
    - [ ] L305: 详细见 [API](/api/#filterBy) -> 详见其[文档](/api/#filterBy)

译法统一建议

- mutate: 突变|变化

**Comment by Jinjiang** [comment]
- `guide/events.md`
    - [ ] L17: 我们把一个单击事件绑定在了方法 `greet` 上。
    - [ ] L104: 和内联表达式相同，内联事件处理器的限制也是**只有一个语句**。 (英文描述的 event handlers 是不是应该明确在 inline JavaScript statement 范围内的？)
    - [ ] L124: 尽管这些事情在方法内可以搞定，我们还是最好让方法专注于纯粹的数据逻辑，而不去处理 DOM 事件的细节。
    - [ ] L175: separation of concern -> 关注点分离 (via wikipedia)

**Comment by Jinjiang** [comment]
- `guide/form.md`

译法统一建议

- radio 单选框
- checkbox 复选框
- select 单选列表
- multiple select 多选列表
- boolean value 布尔值

**Comment by yanxyz** [comment]
select 译为单选列表，不一定对，有时它不限定是哪一种。我通常为”选择框“。

L9: 这个指令<s>会<s>使用

L185: 建议保持原译。原位 or 原地，我觉得还是”原位“好一些，它的意思是在某个东西的原来位置上。

L191: 建议保持原译。这个句子我是特意删掉了”的“。真要加一个的话，我选择在”下面“后面。

L205，L275，L305 建议保持原译。

**Comment by Jinjiang** [comment]
`guide/transitions.md`

```
// handle cancellation
// 取消进入 or 放弃进入

以清理变动或 `enter` 创建的计时器。
以清理 `enter` 中的变动或创建的计时器。

CSS detection -> CSS 探测

然后用 `transition` 特性中：
然后它就可以用在 `transition` 特性上了，用法是相同的：

staggering transitions -> 逐条过渡
```

**Comment by Jinjiang** [comment]
L156：我的继续改进意见：
因而，如果新旧数组之间有大量重叠元素，那么这样的替换效率是非常高的。

**Comment by yanxyz** [comment]
staggering transitions 我原先翻译为 “参差过渡”，后采用旧文档的翻译 “渐进过渡”，这个翻译不知道是不是 @yyx990803 的主意。

**Comment by Jinjiang** [comment]
`components.md`

```
为了让事件更简单，可以直接传入选项对象而不是构造器给 `Vue.component()` 和 `component` 选项。
为了让事情更简单，可以给 `Vue.component()` 和 `component` 选项直接传入一个选项对象，而无需一个实际的构造函数。

自定义元素不在白名单上，将被放在元素的外面，因而渲染不正确。
不在其白名单里的自定义元素将会放到外面，导致渲染不正确。

**binding type modifiers**
**绑定修饰符**
**绑定类型修饰符**

1. `<app>` 组件不知道它的挂载会有什么内容
1. `<app>` 组件不知道其挂载目标上的内容

父组件的内容将被**抛弃**，除非子组件模板包含 `<slot>`。
除非子组件模板包含 `<slot>`，不然父组件的内容将被**抛弃**。

多个组件可以使用同一个挂载点，然后动态地在它们之间切换。使用保留的 `<component>` 元素，动态地绑定到它的 `is` 特性：
你可以为保留元素 `<component>` 动态绑定 `is` 特性，实现在同一个挂载点处动态切换多个组件：

进入与离开平滑地过渡
进入与离开同步过渡
```

`reactivity.md`

```
一个问题是在浏览器控制台打印数据对象时 getter/setter 的格式化不同
一个问题是浏览器控制台在打印转换过 getter/setter 的数据对象时会输出不一样的格式

在计算过程中它把属性记录为依赖
在计算过程中收集所有接触过的属性作为依赖
```

**Comment by yanxyz** [comment]
reactivity.md

一个问题是浏览器控制台在打印转换后的数据对象时输出的是 getter/setter。
我觉得原文表达的是这个意思，我的原译不妥。

在计算过程中收集所有“接触过”的属性作为依赖

**Comment by andyyou** [comment]
@yanxyz 不好意思 想請教 “一个问题是浏览器控制台在打印转换后的数据对象时输出的是 getter/setter。”

One caveat is that browser consoles format getter/setters differently when converted data objects are logged

這句想表達是什麼意思，可否提供個簡單的範例
