### ISSUE TITLE
官网无法识别转义之后的中文锚链接

### ISSUE THREAD

**Issue by qiansen1386** [vuejs/cn.vuejs.org#313]
https://cn.vuejs.org/v2/guide/components.html#%E7%BB%84%E4%BB%B6%E5%91%BD%E5%90%8D%E7%BA%A6%E5%AE%9A
无法识别为
https://cn.vuejs.org/v2/guide/components.html#组件命名约定

这个……算 bug 么？因为咱们的 vueJs 论坛会强制转义中文 url。其他很多站点应该也会转义吧。
具体讨论：https://forum.vuejs.org/t/topic/9484/9

**Comment by Jinjiang** [comment]
嗯，我想了想，觉得都转成中文相对合适一些。
而且其它语言的网址也都这样做了。
如果发现这样的链接就及时提 pr 过来吧。
我也会留意一下这方面的内容。
谢谢
