### ISSUE TITLE
建议翻译的时候，随便更改一下版本号选择里的版本号

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs/cn.vuejs.org#327]
好让用户知道哪个具体的版本，比如我现在就不知道到底是2.1还是2.2，2.3新增的有没有加进来。。

**Comment by Jinjiang** [comment]
这样吧，我今后定期 (也许是每周或每两周) 检查一下英文站是否有更新，如果有的话，只要内容不算非常多，都会第一时间同步到中文版，如果比较多，就先把英文版 copy 过来，用这样的方式保证将来的新内容得意及时的同步且不会漏掉。

已经存在的版本差异通过 社区的力量 case-by-case 的找到并逐步 pr 掉好了。

非常感谢你的建议，这个问题我也早就发现了但是想到的解决办法成本都比较高，直到今天有了这样的想法。
