### ISSUE TITLE
关于按键修饰符的问题

### ISSUE THREAD

**Issue by fefuns** [vuejs/cn.vuejs.org#333]
经过自己实践 .tab, .ctrl, .alt, .shift, .meta并没有执行我自己的事件额。
这是代码：
`<input type="text" @keyup.alt="show" placeholder="按下alt键的时候会弹窗"> 
window.onload = function () {
        var a = new Vue({
            el: '#box1',
            data: {},
            methods: {
                show: function () {
                    alert('您按了alt键')
                }
            }
        });
    }`

**Comment by Silencesnow** [comment]
英文文档中提到两种，一种叫Key Modifiers，另一种叫Modifier Keys，中文都翻译为按键修饰符，其实两者并不相同。
前者比如@key.enter，可以理解为别名，等同于@key.13；
后者是对应按键按下时才开启监听，原文是：“You can use the following modifiers to trigger mouse or keyboard event listeners only when the corresponding modifier key is pressed……”@key.alt是按下alt的时候开启监听，还需要按任意键来触发事件。
题主例子中按alt+任意键会触发弹窗。个人理解，如有问题欢迎指正。

**Comment by fefuns** [comment]
经过测试，alt+其他键可以触发弹窗，的确是这样。不过感觉还是没有解决问题。我觉得以后要是遇到要用alt这类事件的，得慎用

**Comment by Jinjiang** [comment]
支持 @Silencesnow 的建议，另外如文档中 https://vuejs.org/v2/api/#keyCodes 所说，你可以定义一个名为“alt”的 Key Modifiers 来解决这个问题。
谢谢

**Comment by Jinjiang** [comment]
另外我把两个相同的中文翻译做了一些调整，现在可以区分开来理解了
