### ISSUE TITLE
components中翻译小问题

### ISSUE THREAD

**Issue by dingdangnao** [vuejs/cn.vuejs.org#341]
在 components - 杂项 - 编写可复用组件 中

> Vue 组件的 API 来自三部分 - props, events 和 slots ：
> Props 允许外部环境传递数据给组件
> Events 允许组件触发外部环境的副作用
> Slots 允许外部环境将额外的内容组合在组件中。

`Events` 的 翻译有点难懂 觉得翻译成 `允许组件在外部触发时产生作用` 可能会好一点

**Comment by Jinjiang** [comment]
我改成了“允许从外部环境在组件内触发副作用”
