### ISSUE TITLE
本地部署在hexo3.3.6版本无法启动

### ISSUE THREAD

**Issue by HackMi** [vuejs/cn.vuejs.org#358]
npm install 
hexo server
提示：
`AssertionError: <code> tag should not be nested`
通过`<code>((?!</code>).)*<code>`查找发现migration.md:1308 存在`</code >`标签，存在多余的空格
修改后再次hexo server
提示：
`AssertionError: <pre> tag should be coupled: "undefined" <=> "</pre>"`
在render-function.md:549发现`<pre> `标签包含v-for导致被认为未成对

同时发现vuejs.org代码相同无此问题，修改cn.vuejs.org的dependencies中hexo为3.2.2后可正常启动

**Comment by Jinjiang** [comment]
我在 `hexo@3.3.7` 没有发现这个问题，不过我顺便把 `migration.md#L1308` 的空格去掉了。
感谢
