### ISSUE TITLE
v-for不能作用于非html标签吗？

### ISSUE THREAD

**Issue by vectorchen** [vuejs/cn.vuejs.org#405]
`<col span="2" v-for="n in 12"> {{n}} </col>`
这里的col是ivew里面的组件。
控制台抛出：Property or method "n" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by Jinjiang** [comment]
`<col>` 只能用在 `table > colgroup` 下，否则无效
更多问题请在[社区相应的地方](https://github.com/vuejs/vue#questions)提问，这里只讨论文档翻译
谢谢
