### ISSUE TITLE
第一个学习的例子好像就跑不出来

### ISSUE THREAD

**Issue by ifugle** [vuejs/cn.vuejs.org#445]
是我还必须要做哪些操作吗？
我打开了官方提供的示例链接，然后不起作用，我打开的是vue的hello world的例子
https://jsfiddle.net/50wL7mdz/54109/

**Comment by ifugle** [comment]
![image](https://user-images.githubusercontent.com/15215129/29364236-6257777a-82c5-11e7-8434-3529973e3f22.png)

**Comment by ifugle** [comment]
![image](https://user-images.githubusercontent.com/15215129/29364338-a8fee74e-82c5-11e7-9d8a-a6fbe0e1dbd7.png)

**Comment by Jinjiang** [comment]
我这里是工作的，请检查一下网络环境，是不是 vue.js 没有加载成功
谢谢
