### ISSUE TITLE
在windows和mac下显示差别

### ISSUE THREAD

**Issue by HaitianLiu** [vuejs/cn.vuejs.org#476]
位置 🔗 https://cn.vuejs.org/v2/guide/list.html#对象更改检测注意事项

mac下截图：
![image](https://user-images.githubusercontent.com/11406106/30001050-9ae73272-90b4-11e7-84ff-dc02c32e1aba.png)
windows下截图：
![image](https://user-images.githubusercontent.com/11406106/30001131-b0972b52-90b6-11e7-924a-6f91e882e656.png)

有一个小小乱码，这是什么原因造成的？

**Comment by Jinjiang** [comment]
找到问题了，马上修复。
谢谢
