### ISSUE TITLE
计算属性章节错误

### ISSUE THREAD

**Issue by powerformer** [vuejs/cn.vuejs.org#477]
![image](https://user-images.githubusercontent.com/26423749/30001072-3b7e7812-90b5-11e7-9972-b2d3612afae0.png)
实际上却发现可以更新！
![image](https://user-images.githubusercontent.com/26423749/30001074-49f5cbb6-90b5-11e7-9618-0a195d1cfd44.png)
![image](https://user-images.githubusercontent.com/26423749/30001075-4b6778f0-90b5-11e7-861d-5d4527369db4.png)

**Comment by Jinjiang** [comment]
你是怎么更新的？请详细描述重现方法
谢谢
