### ISSUE TITLE
组件 类型检测 这个地方不是很理解 `null` 意思

### ISSUE THREAD

**Issue by sunjichang** [vuejs/cn.vuejs.org#478]
![1504494421614](https://user-images.githubusercontent.com/29514824/30010295-4eec7442-9161-11e7-9e7b-5686fe81381c.jpg)

**Comment by Jinjiang** [comment]
`propA: Number` 就表示 `propA` 是数字类型
同理，如果写成 `propA: null` 就表示 `propA` 可以是任意类型

**Comment by sunjichang** [comment]
嗯，理解了，非常感谢！🙏
