### ISSUE TITLE
欢迎大家一起参与统一格式细节

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/cn.vuejs.org#480]
如题，近期打算集中优化一些翻译的细节，如果诸位在浏览中文翻译时发现如下问题，欢迎发 PR：

1. 中文和英文/数字之间需加空格，几种常见的情况如下：
    * 比如“创建一个 Vue 实例”，“Vue”的左右两侧都是中文，因此两侧都加空格
    * 比如“框架的名字叫做 Vue。”，“Vue”的左侧是中文，加空格，右侧是标点符号，不加空格
    * 比如“详情查阅 [Vue 生命周期](#)”，“Vue”两侧都是中文，因此两侧都加空格，而又因为左侧是链接的末端，所以左侧空格在链接外，右侧空格在链接内
2. 需要为漏掉原文中的反引号 (`) 的地方加一对反引号
3. 如遇锚点未翻译导致锚点失效的，需更新锚点为相应的中文
4. 部分译法需统一：
    * attribute：特性
    * property：属性
    * computed property：计算属性

谢谢

**Comment by shibenli** [comment]
这个能编译提供离线版本的发布吗？pdf、epub、mobi等格式的

**Comment by Jinjiang** [comment]
目前没有这方面的打算，而且离线版本无法即时更新，也不太推荐这样用

**Comment by Jinjiang** [comment]
这个 issue 先关掉了，我稍后把它做成 pr template
