### ISSUE TITLE
”安装 — Vue.js“ jsDelivr CDN 链接错误

### ISSUE THREAD

**Issue by liyuhang1997** [vuejs/cn.vuejs.org#487]
https://cn.vuejs.org/v2/guide/installation.html#CDN

> 也可以从 [jsDelivr](https://cdn.jsdelivr.net/npm/vue/dist.js) 或 [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.0/vue.js) 获取，不过这两个服务版本更新可能略滞后。

其中 jsDelivr 的链接应该是英文站所写的 ```https://cdn.jsdelivr.net/npm/vue/dist/vue.js```  
而不是 ```https://cdn.jsdelivr.net/npm/vue/dist.js```

**Comment by Jinjiang** [comment]
发现了，现在部署的版本非常旧，侧边栏也不太对。有可能是自己昨天部署失误了，我晚上回家用最快速度检查一下
非常感谢
