### ISSUE TITLE
修改文档中的措辞，请不要使用方言

### ISSUE THREAD

**Issue by zjcong** [vuejs/cn.vuejs.org#522]
请修改文档中的如“整个牛项目”，“纯萌”等用词

**Comment by Jinjiang** [comment]
感谢你的建议，从文档本身来说，您提到的这些地方并不影响大家对文档的理解。所以本着尊重当时原译的角度，我们暂时还是选择保留。我们在将来新的翻译更新时会加以注意。未来也会定期 review 现有的翻译，如果确实这些翻译使得很多读者不习惯或者不舒服甚至曲解原意，我们愿意再次讨论。
再次感谢
