### ISSUE TITLE
v-show的一个疑问

### ISSUE THREAD

**Issue by Ts799498164** [vuejs/cn.vuejs.org#524]
文档明确说明，v-show实际上是改变CSS属性实现DOM的展示与隐藏，那么常见的CSS相关的属性无非就是display与visibility。
但是当通过`display：none;`来隐藏的时候，DOM树中对应的节点是不会添加到Render树中的，也就不会发生该节点的渲染，但是该节点是添加到DOM树中的，所以我对文档中对v-show的“渲染”表示疑惑。
我觉得文档中的意思不应该是“渲染”，而是被DOM解析。

**Comment by AmandaYi** [comment]
你先去看看 v-if的原理, 然后对比着看v-show ,在v-if中 是把标签替换成空的注释了,

**Comment by Jinjiang** [comment]
这里的“渲染”就是指它始终会作为一个节点存在于 DOM 树中  (但可以通过 `display` 来控制是否显示在界面上)。
