### ISSUE TITLE
刚刚看到混合这里，看了几遍还不是很清楚

### ISSUE THREAD

**Issue by shleyZ** [vuejs/cn.vuejs.org#525]
我的理解是：组件使用混合对象时，组件就拥有了混合对象里面的所有的属性，相当于把这个组件extend了。
不知道我这样理解对不对，可以把文档写清楚明白些吗

**Comment by Jinjiang** [comment]
> 不知道我这样理解对不对

你理解的是对的

> 可以把文档写清楚明白些吗

请把你认为不清楚明白的点描述一下，或者提供你认为更加清楚明白的文档内容。方便我们再讨论。非常欢迎
