### ISSUE TITLE
条件渲染文档错误

### ISSUE THREAD

**Issue by a49666** [vuejs/cn.vuejs.org#528]
错误：

 ` <h1 v-if="ok">Yes</h1>`

正确：

`  <h1 v-if="'ok'">Yes</h1>`

**Comment by Jinjiang** [comment]
两者写法都对，但意思不一样，前者是指名为 `ok` 的变量，后者是指字符串 `'ok'`。
另外中文文档只是翻译英文版本，这里的代码是和英文版一致的，如果仍有异议，建议直接在英文站开 issue 或 pr 讨论。

谢谢支持

**Comment by a49666** [comment]
感谢指正
