### ISSUE TITLE
不够准确的翻译？

### ISSUE THREAD

**Issue by ug0** [vuejs/cn.vuejs.org#536]
中文译文（来自 [列表渲染 - Key](https://github.com/vuejs/cn.vuejs.org/blob/master/src/v2/guide/list.md#key)）:
> 建议尽可能使用 v-for 来提供 key ，除非 DOM 内容遍历起来非常简单，或者你是有意识的要依赖于默认行为以便获得性能提升。

对应[英文原文](https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/list.md#key)：
> It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains.

相较于原文，“建议尽可能使用 v-for 来提供 key” 可能翻译得不够清楚和准确，也许改为 “建议尽可能在使用 v-for 时提供 key” 更好些？

**Comment by Justineo** [comment]
同意，应该是翻译得不对。第二句也有点问题。

“建议尽可能在使用 `v-for` 时提供 `key`，除非循环输出的 DOM 内容非常简单或者刻意依赖默认行为来获取性能上的提升。”可能更好一些。
