### ISSUE TITLE
一处错字

### ISSUE THREAD

**Issue by SilentDepth** [vuejs/cn.vuejs.org#550]
风格指南 A6 的正文部分，`/src/v2/style-guide/index.md` [第 410 行](https://github.com/vuejs/cn.vuejs.org/blob/6b2e1ba2b991ff74f8509910cc9abb58d95a198e/src/v2/style-guide/index.md#L410)：

原文

> 在插件、混入等扩展中始终为自定义的私有属性使用 `$_` 前缀。并附带一个命名**作用于**以回避和其它作者的冲突 (比如 `$_yourPluginName_`)。

应为

> 在插件、混入等扩展中始终为自定义的私有属性使用 `$_` 前缀。并附带一个命名**作用域**以回避和其它作者的冲突 (比如 `$_yourPluginName_`)。

**Comment by Justineo** [comment]
已修复，谢谢。
