### ISSUE TITLE
接入Atman机器翻译是个不错的选择

### ISSUE THREAD

**Issue by littleweb** [vuejs/cn.vuejs.org#563]
VUE是个不错的框架，https://transgod.cn   前端部分完全使用VUE做组件化和插件化开发，极大的提升了开发效率。做为受益者，我们做为专业的翻译引擎，可以为VUE提供专业的机器翻译服务。

**Comment by Justineo** [comment]
中文文档目前由社区人工维护，我个人理解机翻效果和人工翻译应该还是有差距的吧？是不是自动翻译更适合用于官方未提供翻译版本的语言呢？

**Comment by Jinjiang** [comment]
首先目前 Vue 网站的人工翻译工作是在可承受范围内的，效率上不存在明显的问题。我们会对翻译的品质有比较高的追求。
如果有充足的事实或证据表明您提到的工具可以保障更高的质量，同时没有引入更多我们不可接受的成本或违背社区习惯的流程。我们愿意继续保持开放式讨论。
谢谢

**Comment by Jinjiang** [comment]
鉴于这个话题长期没有讨论，先做关闭处理了。如有后续可再留言或 reopen。
谢谢
