### ISSUE TITLE
slot-scope 应该为 scope

### ISSUE THREAD

**Issue by bison1994** [vuejs/cn.vuejs.org#569]
https://cn.vuejs.org/v2/guide/components.html#作用域插槽
该小节中的 `slot-scope` 应该为 `scope`

**Comment by Justineo** [comment]
https://vuejs.org/v2/guide/components.html#Scoped-Slots

Vue 2.5.0 将 `scope` 重命名为了 `slot-scope`，暂时 `slot` 仍然可用。不过文档里的确应该提一下这一点，我会去英文站提一个相关 issue。

**Comment by Justineo** [comment]
后续请参见：https://github.com/vuejs/vuejs.org/issues/1223。

**Comment by Justineo** [comment]
英文原文已在 API 中加入对 `scope` 的描述。
