### ISSUE TITLE
HTML特性

### ISSUE THREAD

**Issue by hqzh** [vuejs/cn.vuejs.org#586]
特性
Mustache 语法不能作用在 HTML 特性上，遇到这种情况应该使用 v-bind 指令：
<div v-bind:id="dynamicId"></div> 
这同样适用于布尔类特性，如果求值结果是 falsy 的值 (译者注：falsy 不是 false，参考这里)，则该特性将会被删除：
<button v-bind:disabled="isButtonDisabled">Button</button> 

// 但是值为0  和  NaN 该特性没有被删除

**Comment by Justineo** [comment]
这里看起来是原文描述得不严谨，应该要明确描述哪些情况会保留，哪些情况会删除。

**Comment by Justineo** [comment]
后续见 https://github.com/vuejs/vuejs.org/issues/1250。
