### ISSUE TITLE
列表渲染部分的标题在页面加载完后会闪一下

### ISSUE THREAD

**Issue by lijq123** [vuejs/cn.vuejs.org#599]
链接：
https://cn.vuejs.org/v2/guide/list.html#用-v-for-把一个数组对应为一组元素
问题：
打开以后标题是"用 v-for 把一个数组对应为一组元素",然后v-for闪一下跳到最后变成"用 把一个数组对应为一组元素v-for"

**Comment by Jinjiang** [comment]
应该和一个已知问题是同一个问题，正在英文版先讨论修复
@Justineo 有劳也确认一下吧
