### ISSUE TITLE
一点翻译问题

### ISSUE THREAD

**Issue by LeeHDsniper** [vuejs/cn.vuejs.org#619]
https://cn.vuejs.org/v2/guide/instance.html#数据与方法
中

> 英文原文：In addition to data properties, Vue instances expose a number of useful instance properties and methods. These are prefixed with $ to differentiate them from user-defined properties. 

> 中文翻译：除了 data 属性，Vue 实例暴露了一些有用的实例属性与方法。它们都有前缀 $，以便与用户定义的属性区分开来

其中expose是否应当翻译为“显式声明”或者“预定义”更好理解

**Comment by Jinjiang** [comment]
英文 expose 在当前语境就是暴露 (API) 的意思，我觉得您的建议不只是翻译了，而是对原文 expose 本身，建议直接在英文站开个 issue 继续讨论。
谢谢
