### ISSUE TITLE
一个很奇葩的问题

### ISSUE THREAD

**Issue by mikoshu** [vuejs/cn.vuejs.org#623]
列表过渡时，如果列表的循环里 `(value,index) in arr` 列表的key值是 `:key="index"`,这样加的move动画效果是无效的，就是添加和删除有动画，但是数组位置对换没有过渡效果，需要自己去生成key值才可以

**Comment by Justineo** [comment]
这个问题不应该在这里提。Vue 本身的问题请提到 vuejs/vue，这里只处理中文文档相关事宜。谢谢。
