### ISSUE TITLE
“Vue 的一个最明显的特性就是其不太引人注意的响应式系统”这句句子是否有些矛盾？

### ISSUE THREAD

**Issue by tanbowensg** [vuejs/cn.vuejs.org#632]
在“深入响应式原理”一章里，开头有一句：
> Vue 的一个最明显的特性就是其不太引人注意的响应式系统。

对应的英文原文是：
> One of Vue’s most distinct features is the unobtrusive reactivity system. 

这里的“最明显”和“不太引人注意”乍看起来是不是有些矛盾？虽然这两个形容词修饰的是两个不同的中心词，深究起来也可以说是没有问题，但是我们可以换一种措辞让其看来矛盾得不那么明显。

结合上下文的意思，我觉得这里的 unobtrusive 所要强调的是 Vue 的数据模型仅仅是普通的 JavaScript 对象这一特点，以区别于其他框架的特殊的数据模型。所以我觉得 unobtrusive 所要表达的内容类似于“侵入性比较低“之类的意思。这个单词确实有些难以翻译。

所以我觉得不妨把 distinct 翻译为”独特“，一来 distinct 也有独特的意思，而来可以使句子看起来不那么矛盾。

> Vue 的一个最独特的特性就是其不那么引人注意的响应式系统。

**Comment by Justineo** [comment]
同意你说的，这里原先的翻译的确不准确。

> Vue 最独特的特性之一，是其低侵入性的响应式系统。

这样怎么样？@Jinjiang

PS. 我目前在整体 review 所有之前的翻译，还没过到这一篇。

**Comment by Jinjiang** [comment]
感觉“低侵入性”和 unobtrusive 一个更多描述底层逻辑，一个更多描述表象。感觉“低调”这个词更贴切些，不过我有另外一个翻译的建议：

> Vue 的响应式系统并不显眼，但绝对是最独特的特性之一。

**Comment by Justineo** [comment]
我之前想说“低侵入性”的逻辑是说，我们不用主动地过多关注操作数据的 API，Vue 的响应式系统已经为我们做掉了。“不显眼”是直观的意思，但是我觉得并不能太好低表达实际的意思。

早年有个说法叫做“[Unobtrusive JavaScript](https://en.wikipedia.org/wiki/Unobtrusive_JavaScript)”，对应的是把 JS 与 HTML 分离，而不是用内联 `onclick` 等把 JS 和 HTML 耦合在一起的开发方式。这里想表达的是 JS 不影响 HTML 内容的编写，维基百科的中文翻译的是“非侵入性 JavaScript”。Vue 的文档想说的是其响应式系统，并不改变我们操作数据对象的习惯，你只要按正常的 JS 语法修改数据，然后 it just works。

**Comment by Jinjiang** [comment]
那是否可以称为“无侵入性”？毕竟 un- 前缀。低侵入性听起来很没有自信……
我这里没有想夸大事实的意思，只是想讨论一下这是否算是“无侵入性”

**Comment by Justineo** [comment]
或者也叫“非侵入性”？

**Comment by Jinjiang** [comment]
我觉得 OK，稍后我直接改掉好了
