### ISSUE TITLE
attribute 翻译成特性 的疑问

### ISSUE THREAD

**Issue by aristotll** [vuejs/cn.vuejs.org#646]
> https://cn.vuejs.org/v2/guide/syntax.html#%E7%89%B9%E6%80%A7

一般不应该翻译成属性吗

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes

mdn 的中文文档也是这样翻译的

看见特性好久没反应过来 还是看英文原文才知道是 attribute

**Comment by Justineo** [comment]
Property vs Attribute 的翻译是老生常谈的难题了。

Vue 里面相关的有这么几个东西：

* attribtue

  `<div id="app">` 里面的 `id` 是一个 attribtue，这里译为 HTML *属性*。

* property

  `this.data.name` 里面的 `name` 是 `this.data` 的一个 property，这里译为*特性*。

* prop

  `<my-component foo="bar">` 这里面，如果 `foo` 在 `MyComponent` 里的 `props` 注册过，那么它就是一个 prop，否则他就是一个普通的 attribute。prop 保留了原文没有翻译。

在有部分内容里的描述中同时涉及了这三个概念中的两个以上，所以必须要有一个区分的翻译方案。那么考虑到一致性，就始终保持三者有不同的翻译策略了。之前 W3C 的规范中文翻译中也是把 attribtue 译为“特性”的。

**Comment by SLin0218** [comment]
建议`html attributes`可以使用`属性（Attribute）`，第一眼看上去不知道是个什么。

**Comment by SLin0218** [comment]
第一眼看上去不知道是什么。
- 建议`html attributes`可以使用属性`（Attribute）`，或保留原文，毕竟大部分人都认识，
