### ISSUE TITLE
翻译内容不一致

### ISSUE THREAD

**Issue by wangshantao** [vuejs/cn.vuejs.org#664]
![image](https://user-images.githubusercontent.com/14883268/35846314-1e919c86-0b51-11e8-9dbe-3d8d084afd54.png)
圈里英文都是Watchers，应该统一下吧？

**Comment by Jinjiang** [comment]
会统一到侦听器。参考：https://github.com/vuejs/cn.vuejs.org/wiki
我马上改一下。
谢谢
