### ISSUE TITLE
实例属性：vm.$refs的详细说明的疑问

### ISSUE THREAD

**Issue by LiuwqGit** [vuejs/cn.vuejs.org#696]
先阐述我的观点：
`vm.$refs` 表示 一个对象，持有已注册过 ref 的所有子组件**或者DOM元素**。

特殊属性`ref`:
`ref` 被用来给元素或子组件注册引用信息。引用信息将会注册在父组件的` $refs `对象上。如果在普通的 DOM 元素上使用，引用指向的就是 DOM 元素；如果用在子组件上，引用就指向组件实例：
``` 
<!-- vm.$refs.p will be the DOM node -->
<p ref="p">hello</p>

<!-- vm.$refs.child will be the child comp instance -->
<child-comp ref="child"></child-comp>
```
从这个属性描述中，我看出来，`vm.$refs.p`表示为DOM节点。

以下，是我在实际工作中遇到，然后截图。
DOM元素注册的引用信息：
![DOM元素](https://user-images.githubusercontent.com/7065327/37953408-68210ab2-31d5-11e8-9100-4c4d75c026b8.png)

子组件注册的引用信息：
![子组件](https://user-images.githubusercontent.com/7065327/37953562-d2f94e26-31d5-11e8-8ea6-6391b1c6d3bf.jpg)

所以，我认为，`vm.$refs`表示一个对象，持有已注册过`ref`的所有子组件和已注册过的DOM元素

不知道，我以上理解的，对不对，请指正。

**Comment by Justineo** [comment]
没问题，`ref` 可以写在自定义组件上，也可以写在原生 DOM 元素上。这样 `$refs` 里对应的分别是组件实例和 DOM 元素。

**Comment by LiuwqGit** [comment]
那我去英文站问问。
