### ISSUE TITLE
demo有误

### ISSUE THREAD

**Issue by riskers** [vuejs/cn.vuejs.org#70]
[自定义指令-指令实例属性](http://cn.vuejs.org/guide/custom-directive.html#指令实例属性)中的示例:

```
<div id="demo" v-demo:hello.a.b="msg"></div>
```

应为

```
<div id="demo" v-demo:#000.a.b="msg"></div>
```

否则文字是白色的，背景也是白色的。一开始还以为指令没有生效。

**Comment by yanxyz** [comment]
嗯，在“结果”那个位置查看源码，示例的 bind 钩子真实代码为：

``` js
bind: function () {
    console.log('demo bound!')
}
```

跟说的不一样，指令实际上是生效的。等 @yyx990803 修正。

**Comment by yyx990803** [comment]
已修正
