### ISSUE TITLE
是否有必要需要声明未翻译的内容？

### ISSUE THREAD

**Issue by byzf** [vuejs/cn.vuejs.org#701]
例如英文文档Guide中的Components In-Depth，如果只看中文文档，很容易遗漏这个章节，能否在文档的某处提供一个未翻译的内容列表，并保留相应的英文文档链接？

**Comment by Jinjiang** [comment]
components 部分的文档是上个月刚更新的，我们正在翻译当中，一般情况下中文官网会以周为单位同步英文版的更新，这次英文版 components 和 cookbook 先后有大幅度新增内容，所以有一些滞后。还请谅解。
这个 issue 我会开着，直到我们把 components 的内容更新上线。
谢谢

**Comment by Jinjiang** [comment]
#714 #712 #706 #705 #704 #702
