### ISSUE TITLE
http://cn.vuejs.org/guide/components.html#使用_Slot_分发内容   文档是否有误？

### ISSUE THREAD

**Issue by Alexis374** [vuejs/cn.vuejs.org#71]
"注意两点：
`<app>` 组件不知道它的挂载会有什么内容。这取决于 `<app>`的父组件。"

这里是否应该是取决于`<app>`的子组件

**Comment by Alexis374** [comment]
`<app>`，被github过滤了

**Comment by yanxyz** [comment]
帮你把 `<app>` 用反引号包裹了。

原文是

> The `<app>` component do not know what content may be present inside its mount target. It is decided by whatever parent component that is using `<app>`.

这里我译得不是非常清楚，重译：

> `<app>` 组件不知道它的挂载点会有什么内容，挂载点的内容是由 `<app>` 的父组件决定的。

可以看 http://cn.vuejs.org/guide/components.html#单个_Slot 体味一下。
