### ISSUE TITLE
这个 ‘thuthiness’ 是否拼写错误了？

### ISSUE THREAD

**Issue by HydeSong** [vuejs/cn.vuejs.org#717]
<img width="657" alt="wx20180425-110220 2x" src="https://user-images.githubusercontent.com/8867413/39224193-967d96f0-4878-11e8-83ac-027446bf6384.png">
请查阅 [wiki](https://github.com/vuejs/cn.vuejs.org/wiki) 术语翻译约定表格最后一行

**Comment by Justineo** [comment]
是的，已修正，谢谢指出。

**Comment by HydeSong** [comment]
OK
