### ISSUE TITLE
文档里要不要交代一下 v-for 和 v-on 结合的时候怎么在 method handler 中得到 item 数据？

### ISSUE THREAD

**Issue by Jinjiang** [vuejs/cn.vuejs.org#72]
如题，我自己也有点不太熟悉 v1.0 的新语法，比如 `v-for="item in items" v-on:click="foo"` 的时候 `foo` 怎么得到 `item`，我注意到 `list.md` 和 `events.md` 都没提这件事

**Comment by yyx990803** [comment]
直接 `@click="foo(item)"` 即可

是可以提一下

**Comment by Jinjiang** [comment]
那 custom directive 里是不是没有机会拿到 `item` 了？`this.item` 应该不行吧

**Comment by Jinjiang** [comment]
所以只能写成文档中的“Inline Statement Handler”咯？这样似乎不太好吧，是否可以在 method handler 里通过 `this.item` 得到呢？感觉这样蛮方便的，也就不需要 inline statement handler 了

**Comment by yyx990803** [comment]
这样的话 method 的 `this` context 就是不确定的了... 会让代码很难理解的。

**Comment by Jinjiang** [comment]
这会导致相同的逻辑在普通场景可以直接 method handler，然后通过 `this` 拿到相应的数据，而在列表中则不行，必须通过 inline 的方式，而且除了 `item` 其它的其实都可以通过 `this` 拿到，不需要在 template 里显示写明，总觉得不方便就是了……

而且在 `v-for` 里 `item` 和 `items` 之外的 key 应该都是可以被直接识别的，现在 template 里的 context 和 method handler 里的 this context 差一点点，对应不起来

**Comment by yyx990803** [comment]
methods 的 API 设计遵循的是一个简单的道理：任何 method 内部的 `this` 永远指向其所属的 vm 实例。如果一个 method 的 `this` 会因为其在模板中被调用的位置而改动，那么 `vm.method()` 该如何理解呢？

在模板里的情况更类似于：

``` js
vm.items.forEach(function (item) {
  vm.method(item)
})
```

`method` 并不存在于 for 的 scope 上，而是存在于 vm 上。

**Comment by Jinjiang** [comment]
got

**Comment by realgeoffrey** [comment]
yes
