### ISSUE TITLE
关于广告

### ISSUE THREAD

**Issue by laysdra7265** [vuejs/cn.vuejs.org#729]
我知道这个应该是因为赞助商的原因，广告是无所谓，但是只需要几个具侵略性的广告就能把用户体验打死。
比如说首页的介绍影片好了，我还没见过哪家的产品介绍影片会先看别人家产品广告30秒的，这可是入口站耶，多亏了官网还做的这么漂亮。播放的时候右上角还会有一个10年免费vip的按纽卡在那边，我还要翻转手机全屏才能看到被遮住的部分。
最后是每个文档的右上方都被插入一个什么极客的广告，不能关闭，造成在手机版面上文档的标题和文档开头的简介区整个大变形(别说手机，就算是电脑端，在标题边上放上广告侵入感也是够强劲的了)，很影响阅读，白费了网站做成了响应式架构，我一直分心去看那个广告。实在是受不了所以来吐槽了。

**Comment by emptymalei** [comment]
说的应该是优酷的广告，只是因为视频是 host 在优酷的吧？

**Comment by laysdra7265** [comment]
查了一下发现那个碍眼的广告貌似是vuejs创建人放的？感觉有些无语了，这样说啥也没用了吧wwwww,，其实我本来还以为是被恶意插入广告什么的。

**Comment by Justineo** [comment]
关于视频，英文版是放在 Vimeo 上的，但 Vimeo 在墙外，所以目前临时放在了优酷。如果有更好的托管站点我们也是乐意切换的。我记得当时 B 站也试过了，有点问题才用了优酷。可以让 @Jinjiang 解答一下。

**Comment by Justineo** [comment]
关于广告，对于广告主来说没有 ROI 就没有投放广告的价值，所以被用户看见是满足预期的（而且毕竟一开始阅读内容，广告就滚动到上一屏去了）。开源不等于义务劳动，希望可以理解。

另外，如果实在对广告感到反感，可以使用 AdBlock/Stylish 之类的浏览器扩展来处理。

**Comment by laysdra7265** [comment]
嗯我也明白開源不是義務，目前也是開了反外掛插件把那個廣告屏障了。
主要是想說直立的廣告大概不算是行動裝置友善的，在我手機上幾乎是和標題內文區一邊一半的情況(雖然確實只要看完標題和標題下方部分文字就可以往上滑掉了，但是標題被擠壓感覺還是蠻彆扭的)，如果是橫幅的廣告放在標題正上方感覺就會好很多，或者放個關閉按鈕在邊上也行。至於影片我也想過了確實是有牆的問題，那其實現在能有影片播放就已經很不錯了。辛苦你們了，祝你們能夠繼續把社群營造的更好。

**Comment by Jinjiang** [comment]
目前优酷这边的广告问题还在沟通中，我同步一些情况：

1. 文档页面中左右两侧的广告确实是我们有意加上的，这也是 Vue.js 回馈 sponsor 支持的方式之一，所以还是希望大家能够理解🙏。具体效果如截图所示。如果大家在各自的设备看到不一样的效果，觉得体验无法接受，可以将自己设备的截图分享至此，我们可以再讨论。

    * <img width="1440" alt="2018-05-07 4 17 33" src="https://user-images.githubusercontent.com/206848/39692191-b6ebc670-5212-11e8-8e0d-224fb53f538c.png">PC 端效果截图

    * <img width="1440" alt="2018-05-07 3 32 43" src="https://user-images.githubusercontent.com/206848/39692220-d116e67e-5212-11e8-9842-acdd8129220b.png">手机端 portrait 效果截图

    * <img width="1440" alt="2018-05-07 3 32 47" src="https://user-images.githubusercontent.com/206848/39692222-d1494fba-5212-11e8-8583-fccec2df0ef0.png">手机端 landscape 效果截图

2. 视频的部分，目前除了优酷，我们也在考虑哔哩哔哩，从对哔哩哔哩试用效果来看，我们有几点顾虑，在此抛出来和大家一起讨论

    * 哔哩哔哩的弹幕功能是一把“双刃剑”，一方面可以拉近大家的距离，另一方面显得不够正式，同时有被“水”或恶意评论的风险，这些内容出现在 Vue 首页会觉得不妥

    * 优酷的播放器相对干扰元素少一些，哔哩哔哩的播放器界面上有热门视频推荐的 bar、弹幕框等干扰元素，从宣传效果上来看，会造成用户不够专注的了解和观看视频，或流失

    * 优酷的播放器存在一点点的响应式问题，即在视频播放过程中，不会响应屏幕尺寸的变化，这一点在手机屏幕由 portrait 到 landscape 切换时尤为明显，当然这算是个 bug，未来修复的可能性是蛮高的

    * 一些其它考量
        * 优酷的广告可以通过付费的方式去除，有一定的开销，[付费标准](http://cloud.youku.com/services/info?serid=1)，或者用等价的 sponsor 的回馈方式来跟优酷谈
        * 哔哩哔哩的新用户注册成本非常高，要答很多题……个人觉得十分崩溃
        * B 站的长期可用性是否会是一个问题 (由 A 站前段时间的状况联想到的，希望 B 站的同学看到这则讨论不要介意)

<img width="1440" alt="2018-05-07 3 32 56" src="https://user-images.githubusercontent.com/206848/39692713-3880f4de-5214-11e8-9435-218ee68237fa.png">哔哩哔哩 PC 端效果截图
<img width="1440" alt="2018-05-07 4 15 47" src="https://user-images.githubusercontent.com/206848/39692717-3a7bd1b4-5214-11e8-9fbc-c2a036377e92.png">哔哩哔哩手机端 portrait 效果截图
<img width="1440" alt="2018-05-07 4 15 46" src="https://user-images.githubusercontent.com/206848/39692716-39359484-5214-11e8-9e4f-19536622aecb.png">哔哩哔哩手机端 landscape 效果截图
<img width="1440" alt="2018-05-07 4 15 26" src="https://user-images.githubusercontent.com/206848/39692685-22f6fafa-5214-11e8-8e3f-c52e935ead4f.png">弹幕 PC 端效果截图
<img width="1440" alt="2018-05-07 4 15 58" src="https://user-images.githubusercontent.com/206848/39692686-23263144-5214-11e8-8821-b1fa0ca53bdd.png">弹幕手机端 portrait 效果截图
<img width="1440" alt="2018-05-07 4 16 10" src="https://user-images.githubusercontent.com/206848/39692688-235581f6-5214-11e8-9238-ac3ff8cb3dbc.png">弹幕手机端 landscape 效果截图

以上

谢谢

**Comment by laysdra7265** [comment]
你說的也沒錯。。沒考慮到彈幕問題，這樣確實也是不適合放首頁，干擾也很大。如果有辦法可以取消字幕就好了，是說我當初註冊的時候都是上網找題庫過的，真的很難，不過只要一次過之後就沒啥事了，難道他們最近問題難度又增加了嗎?
至於可用性，我覺得應該還好吧。

**Comment by yyx990803** [comment]
视频广告的问题，这是放置的时候没有考虑到的问题，其实在我个人看来与其让用户 30 秒的广告还不如不要这个视频。

文档内部页面的广告是 Vue 项目收入来源之一，放在页首不影响你阅读具体的文档内容，如果这也接受不了我们无能为力，请你自己调整预期。

**Comment by Turing-Chu** [comment]
fork 一份自己的吧。反正放广告体验很不好。

**Comment by yyx990803** [comment]
@Turing-Chu 可以请你别用 Vue 吗？用着免费的东西还抱怨广告让开发者的体验很不好。
