### ISSUE TITLE
一处翻译的讨论

### ISSUE THREAD

**Issue by zry656565** [vuejs/cn.vuejs.org#73]
在“对比其他框架”中：

英文版：Interestingly, quite a few Angular 1 issues that are non-existent in Vue are also addressed by the design decisions in Angular 2.
中文版：有意思的是，Angular 1 的许多问题（Vue 没有）也因为 Angular 2 的设计决定而解决。

中文版有点不知所云，我的理解是：有意思的是许多 Angular 1 中存在而 Vue 中不存在的问题，依旧出现在了 Angular 2 的设计方案中。

不过我目前还没使用过 Angular 1 和 Angular 2，所以不是很清楚翻译得对不对。

**Comment by zry656565** [comment]
refer:
1. http://cn.vuejs.org/guide/comparison.html
2. http://vuejs.org/guide/comparison.html

**Comment by yanxyz** [comment]
原文关键是理解 address 的意思，比如短语 address the problem  的意思是解决问题。Angular 2 换了设计思路，避免了 Angular 1 的许多问题。

**Comment by zry656565** [comment]
@yanxyz 感谢解疑。
