### ISSUE TITLE
Bug: 监听键盘事件时， 只有在button 被鼠标点击一次后 ，键盘事件才会生效

### ISSUE THREAD

**Issue by KevinLv** [vuejs/cn.vuejs.org#739]
示例如下：

`<div id="app1"><button @keyup.13="warn">提交</button></div>`
`var app11 = new Vue({ el:"#app1", methods:{warn:function(){alert("提交")}}})`

测试只有鼠标点击 button  过后，键盘事件才会生效。

**Comment by Justineo** [comment]
你好，需要先 focus 到按钮上，键盘事件才会生效的。你提供的代码一切正常，不是 bug。

**Comment by KevinLv** [comment]
您好！
因为在测试的时候只弄了个button，才有此现象。
但是假设用户输了用户名、密码，不按table将focus到登录按钮上直接 enter 仍然是没效果。

因为我在用百度的登录发现没有focus到按钮上，focus在验证码框，即我输入验证码后直接按enter, 键盘事件依然有效。 可优化，用户体验更好！ 
      谢谢！

**Comment by Justineo** [comment]
你描述的场景和 Vue 本身没有关系。这种情况你应该把监听器写到输入框上而不是按钮上。
