### ISSUE TITLE
建议把反例和正例顺序反置

### ISSUE THREAD

**Issue by stanleyxu2005** [vuejs/cn.vuejs.org#766]
我是从angular社区转过来的，非常感谢Vue有非常友好的社区和中文文档，帮助我很快的上手。我今天看代码规范这一章节的时候，我发现文档里面把反例置于好例子之前。这是一个困扰我多年的问题了，以前读书的时候做选择题的时候也一直遇到。这就是如果正确的答案放在第一位，那么我可能会更主动的记忆并且理解。就像你去听一个演讲，可能45分钟过后，你唯一记得的就是开场的一个slogan。不知文档维护者和开发团队是否觉得把反例置于好例子之后会更便于理解呢？

https://github.com/vuejs/cn.vuejs.org/blob/master/src/v2/style-guide/index.md

如果描述的内容是解释某个反例的，那么可以把介绍一同放在反例上面。
例如https://cn.vuejs.org/v2/style-guide/#%E6%B2%A1%E6%9C%89%E5%9C%A8-v-if-v-if-else-v-else-%E4%B8%AD%E4%BD%BF%E7%94%A8-key-%E8%B0%A8%E6%85%8E%E4%BD%BF%E7%94%A8

**Comment by JobbyM** [comment]
reactjs 文档也是将反例置于前边，例如https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized，大概这是一种风格？

**Comment by stanleyxu2005** [comment]
已经在英文社区创建帖子，英文文档改了，相信中文的也会改。
至于@jobbym的说法，其实除了参考facebook的做法，也可以参考google的，毕竟react不是标准（不然也就没有vue了）换一个角度想，如果每一个code style只允许用一句话来描述，你是选正例还是反例？

**Comment by Justineo** [comment]
> 换一个角度想，如果每一个code style只允许用一句话来描述，你是选正例还是反例

这是一个逻辑谬误。现在讨论的是正例反例先后的问题，而不是哪个重要的问题，哪个是必须的这个并没有任何争议。

我理解反例放在前，是因为有很多人可能在实践中已经用了这样的 anti-pattern 或者遇到了错误（或者说没遇到过，如果不看文档也可能有这样的倾向），这个时候再适时提出正确方法，是很通顺的。正例在前，这样的用户往往不能提前理解对应需要避免的坑是什么。

> 其实除了参考facebook的做法，也可以参考google的，毕竟react不是标准

随便找了一个 Google 的 [JS 编码规范](https://google.github.io/styleguide/jsguide.html#jsdoc-template-parameter-types)：

> Bad:
>
> ```js
> const /** !Object */ users = {};
> const /** !Array */ books = [];
> const /** !Promise */ response = ...;
> ```
>
> Good:
>
> ```js
> const /** !Object<string, !User> */ users = {};
> const /** !Array<string> */ books = [];
> const /** !Promise<!Response> */ response = ...;
>
> const /** !Promise<undefined> */ thisPromiseReturnsNothingButParameterIsStillUseful = ...;
> const /** !Object<string, *> */ mapOfEverything = {};
> ```

另外，我看了一下，ESLint 的规则说明里多数例子也都是反例在前，比如[这个](https://eslint.org/docs/rules/no-debugger#rule-details)。

**Comment by Jinjiang** [comment]
我理解 style-guide 更多是个纠正的过程，因为已经有 guide 和 api 在更明显的位置了，当然我不是为了反驳先正例的观点，只是觉得有各自的考量，两种写法我个人都充分尊重，同时也尊重英文原版的编排。
Anyway，我们可以继续在英文版讨论，包括这里的所有人。
为了避免内容过于分散，这个 issue 我关掉了。 🤝

**Comment by stanleyxu2005** [comment]
谢谢@Justineo回应，很有意思。

Vue之所以好，Vue不和你介绍茴香豆的108种写法，而是直接给你开发者认为最优雅的实现方式。这样方便快速记忆，快速上手。至于很多繁琐的细节，只有等到需要用到的时候才去了解（比如webpack的进阶配置）。

我开这个issue，并不是来找茬的。我对错误正确摆放顺序的问题，有一些感触。以前中学学习英文的时候，老师给很多错误的示范，然后告诉你正确的怎么说。（包括笔试的时候，大量的选择题也是这样。）但是到了国外，你发现那些语法题根本做不来的外国留学生，口语讲的非常好。你问他，为什么你知道要这么讲，他和莫名的和我说，除了这样讲，还能怎么讲？

但到了文档环节，大量的错误示范，很多我觉得是大开脑洞的，都罗列出来，这和Vue简介的设计以及其他文档的表述，在叙述风格上略有出入。希望这个issue是建设性的讨论，而不要变成了卷筒纸是因为撕的那面朝外还是朝里的问题。
