### ISSUE TITLE
vue文档菜单栏没显示出来

### ISSUE THREAD

**Issue by sunshixiong789** [vuejs/cn.vuejs.org#779]
vue官方文档没有显示菜单栏

**Comment by sunshixiong789** [comment]
就是那个api文档没有左边的菜单，其他的还没注意

**Comment by Jinjiang** [comment]
无法重新你的问题，请检查一下网络情况，或提供更多信息帮助我们排查你的问题
谢谢

**Comment by sunshixiong789** [comment]
![image](https://user-images.githubusercontent.com/31101988/42731881-1c1a9082-8849-11e8-9e15-8d5280bc9d92.png)

The problem is still unresolved

**Comment by sunshixiong789** [comment]
![image](https://user-images.githubusercontent.com/31101988/42731904-acc0db46-8849-11e8-8f35-f976a1265ebb.png)

I have reinstalled the browser, and I still have this problem

**Comment by sunshixiong789** [comment]
I'm using the Google browser

**Comment by sunshixiong789** [comment]
I think it's a problem with my browser, which I won't have after I've completely reinstalled the browser

**Comment by sunshixiong789** [comment]
谢谢你的回答
