### ISSUE TITLE
Can you remove this ad from page?

### ISSUE THREAD

**Issue by Turing-Chu** [vuejs/cn.vuejs.org#781]
As an opensource website. I do not think there should be an ad appeared in pages: [极客时间](https://github.com/vuejs/cn.vuejs.org/blob/master/themes/vue/layout/partials/ad.ejs)

**Comment by Justineo** [comment]
Hi，首先谢谢你的建议。因为你是在中文站发的问题，那么我就直接用中文答复你吧。

开源不等于免费，甚至采用 GPL 协议的项目都允许用于商业目的或直接销售盈利。所以你提出的要求在逻辑上是不成立的，开源与否和是否应该有广告**没有因果关系**。另可参见 #729。

如果你能够用更好的方式资助 Vue 项目，我相信换一种方式也是可以考虑的。
