### ISSUE TITLE
中文文档中可能存在的语病

### ISSUE THREAD

**Issue by xlgp** [vuejs/cn.vuejs.org#795]
在阅读Vue中文文档时,发现文档中可能存在一些语病:
例如: 
> 为什么......的原因.

-  [他们可能会花很多个小时去找出模板为什么无法正确更新的原因。](https://cn.vuejs.org/v2/guide/components-edge-cases.html#%E9%80%9A%E8%BF%87-v-once-%E5%88%9B%E5%BB%BA%E4%BD%8E%E5%BC%80%E9%94%80%E7%9A%84%E9%9D%99%E6%80%81%E7%BB%84%E4%BB%B6)
- [这也就是为什么 Vue 不支持 IE8 以及更低版本浏览器的原因。](https://cn.vuejs.org/v2/guide/reactivity.html#%E5%A6%82%E4%BD%95%E8%BF%BD%E8%B8%AA%E5%8F%98%E5%8C%96)
- [这就是为什么会有一个 Babel 插件，用于在 Vue 中使用 JSX 语法的原因](https://cn.vuejs.org/v2/guide/render-function.html#JSX)

_为什么_或_的原因_二者留其一,是否会更好

**Comment by Justineo** [comment]
欢迎 PR 😄
