### ISSUE TITLE
纠正

### ISSUE THREAD

**Issue by followyounger** [vuejs/cn.vuejs.org#803]
”然而，不同的是计算属性是基于它们的依赖进行缓存的。计算属性只有在它的相关依赖发生改变时才会重新求值。“

两个都是说的计算属性，应该改为

”然而，不同的是方法是基于它们的依赖进行缓存的。计算属性只有在它的相关依赖发生改变时才会重新求值。“

**Comment by Justineo** [comment]
没有错。方法的返回值不会进行缓存。

不过我觉得的确可以优化一下：

> 然而，不同的是计算属性是基于它们的依赖进行缓存的，只在相关依赖发生改变时它们才会重新求值。
