### ISSUE TITLE
用词修正

### ISSUE THREAD

**Issue by dandanbu3** [vuejs/cn.vuejs.org#836]
[现在你想要在网站上快速加入一个博客，但不想新起一台服务器去部署一个 WordPress 实例 (或任何基于数据库的 CMS)。](https://cn.vuejs.org/v2/cookbook/serverless-blog.html)
“快速加入一个博客”改为“快速添加一篇博客”是否更好

[Nuxtent 将 Vue.js 和 Markdown 很好地集成了起来，让你完全生活在 Vue.js 的世界里。](https://cn.vuejs.org/v2/cookbook/serverless-blog.html)
“很好地集成了起来”改为“很好地整合起来”是否更好

**Comment by Justineo** [comment]
欢迎直接提交 PR 😄
