### ISSUE TITLE
页面导航不一致

### ISSUE THREAD

**Issue by Heanes** [vuejs/cn.vuejs.org#843]
默认进入“教程”页面，左侧为“基础”-“组件”，手机端发现左侧导航与电脑端导航不一致，手机端导航为“基础”-“组件基础”，并多出“深入了解组件”。可见截图如下：
### 电脑端
![image](https://user-images.githubusercontent.com/2138008/48750160-ce0e9580-ecb8-11e8-8663-b8dc4a9bfa9b.png)

### 手机端
![image](https://user-images.githubusercontent.com/2138008/48750155-c7801e00-ecb8-11e8-8d81-6494686b3efa.png)
然后用电脑点访问对应的地址：
![image](https://user-images.githubusercontent.com/2138008/48750206-fb5b4380-ecb8-11e8-80fa-28b535d8c818.png)
可见**左侧导航内容**不一致，并且**顶部导航也不一致**

**Comment by Justineo** [comment]
是否是缓存的原因？我这里无法复现你第一个图的问题。

**Comment by Heanes** [comment]
> 是否是缓存的原因？我这里无法复现你第一个图的问题。

@Justineo 不是缓存原因，第一个图是目前电脑端正常访问的页面，第2个图是手机端访问出现的，然后我发现用电脑端也能看到。你可以访问[https://cn.vuejs.org/v2/guide/components-registration.html](https://cn.vuejs.org/v2/guide/components-registration.html)这个页面试试

**Comment by Justineo** [comment]
你把 vuejs.org 下面的所有缓存都清掉试试，包括 service worker。

**Comment by Heanes** [comment]
我用隐身模式打开发现就是下面的那种了，是正常的了，很奇怪。。可以关掉这个issue了。
