### ISSUE TITLE
能否贡献文章翻译

### ISSUE THREAD

**Issue by ludanxer** [vuejs/cn.vuejs.org#844]
您好。看到[Cookbook](https://cn.vuejs.org/v2/cookbook/client-side-storage.html)中还有几篇文章没有进行翻译。而[README](https://github.com/vuejs/cn.vuejs.org/blob/master/README.md)的`如何参与贡献`中，并没有提及可以翻译整篇文章的内容。
> 同步英文站点最新的改动到这里
> 修复错别字或错误的书写格式
> 发 issue 讨论译法或书写格式
> 发 issue 讨论部署或协作流程上的问题

请问这些尚未翻译的英文文章是接受PR 的嘛？还是已经有人在翻译了呢？

**Comment by Jinjiang** [comment]
接受 PR，非常欢迎 🙂
需要额外解释一下，cookbook 的英文版更新也是相对零散的，所以我们在有限的精力之下刻意放慢了翻译节奏，希望可以理解

**Comment by ludanxer** [comment]
好的，谢谢。很感谢你们的付出。
