### ISSUE TITLE
为什么只有中文的首页还是推1.0.10。。。

### ISSUE THREAD

**Issue by qiansen1386** [vuejs/cn.vuejs.org#86]
![q -20151218164900](https://cloud.githubusercontent.com/assets/1759658/11892917/5100fc6e-a5a7-11e5-88e8-00867a8d8c8e.png)
![q -20151218164908](https://cloud.githubusercontent.com/assets/1759658/11892918/5102a190-a5a7-11e5-95ad-652c8b852e13.png)
![q -20151218164920](https://cloud.githubusercontent.com/assets/1759658/11892916/50ffc8da-a5a7-11e5-8cf1-08793d1f0d54.png)

**Comment by yyx990803** [comment]
已更新

**Comment by qiansen1386** [comment]
感谢大牛！:joy:
