### ISSUE TITLE
网站打不开，请求部署一份 Github Pages 谢谢！

### ISSUE THREAD

**Issue by zoyen** [vuejs/cn.vuejs.org#873]
所在地: 吉林省
打开网站一个页面通常要10分钟，我不清楚其他地区是否有这情况，请求部署一份 Github Pages 谢谢！

**Comment by Justineo** [comment]
能否打开 Network Panel 看一下究竟是什么内容加载缓慢呢？

**Comment by zoyen** [comment]
[![Snipaste_2019-03-11_12-58-48.png](https://i.loli.net/2019/03/11/5c85eb5f6a081.png)](https://i.loli.net/2019/03/11/5c85eb5f6a081.png)
-
[![Snipaste_2019-03-11_13-01-45.png](https://i.loli.net/2019/03/11/5c85ebcb45c29.png)](https://i.loli.net/2019/03/11/5c85ebcb45c29.png)

**Comment by zoyen** [comment]
### 50秒打开了，这已经是最好的情况了，虽然缺少一些资源logo什么的没加载出来。
[![Snipaste_2019-03-11_13-12-42.png](https://i.loli.net/2019/03/11/5c85ee6ca8b71.png)](https://i.loli.net/2019/03/11/5c85ee6ca8b71.png)

**Comment by zoyen** [comment]
自己fork部署了一份gh pages。
[https://vue.shafc.me](https://vue.shafc.me)
