### ISSUE TITLE
部署到国内服务器

### ISSUE THREAD

**Issue by yyx990803** [vuejs/cn.vuejs.org#89]
@yanxyz @Jinjiang 

最近有同学反映 GitHub pages 从国内访问很慢，考虑能不能把中文官网部署在国内。
1. 只需要静态资源服务器即可
2. 需要修改 Makefile 部署脚本
3. 我来修改 DNS 指向

不知两位谁有时间/兴趣帮个忙。社区如果有同学愿意帮忙也欢迎。

**Comment by yanxyz** [comment]
可以呀。国内我没有服务器，要不你在微博上问一下，看看有没有人帮忙。或者试试 https://coding.net。

**Comment by limichange** [comment]
大概需要多少性能的服务器呢？

**Comment by limichange** [comment]
最好加上百度统计，Google的在国内不是很好用的。

**Comment by limichange** [comment]
@yanxyz 我提供一台，然后将资源放在七牛的CDN上。这样访问的效果会不错。

**Comment by limichange** [comment]
比如这样http://7xpmhw.com1.z0.glb.clouddn.com/guide/installation.html

**Comment by yyx990803** [comment]
可以啊，要不中文文档的广告就去了吧，反正国内应该也没人会点...

**Comment by limichange** [comment]
要不先把DNS转到这个试试？

**Comment by yyx990803** [comment]
我放了个 cn-stage.vuejs.org，先看看效果如何，估计要等几个小时才生效

**Comment by limichange** [comment]
👌

**Comment by limichange** [comment]
@yyx990803 国内对域名有备案验证，我想想其他办法

**Comment by limichange** [comment]
@yyx990803 CNAME地址 微博私信了

**Comment by jas0ncn** [comment]
@yyx990803 尤大你好，我是深圳大学公众号的负责人，我用我们的服务器和域名做了个镜像的文档，一开始是为了方便团队内部学习。
链接：http://vue.iszu.cn/
目前我还是clone下源代码然后generate之后部署上去的。如果需要可以联系一下看看怎么做。

**Comment by limichange** [comment]
[vuejs.org.cn](vuejs.org.cn) 😊

**Comment by yyx990803** [comment]
@limichange 这个域名可以...

**Comment by limichange** [comment]
@yyx990803 很快的哟，DNS是万网的。直接挂在coding的page服务上，维护也很方便。如果想用这个域名做点什么告诉我就好😊

**Comment by yanxyz** [comment]
@limichange 怎么发布到这个服务器上？

**Comment by limichange** [comment]
@yanxyz 和github一样的，这个是项目地址https://coding.net/u/limichange/p/cn.vuejs.org/git。

目前是手工维护，直接将官方的gh-pages拉取到这个项目的gh-pages。然后就完成更新了。

**Comment by yanxyz** [comment]
@limichange gh-pages 分支的文件是如何到服务器上的呢？手工复制还是？

**Comment by limichange** [comment]
@yanxyz 自动的。和github的pages服务一样。

**Comment by limichange** [comment]
@yanxyz 如果你想亲自操作，我可以将你加入到项目中。把coding账号提供给我就好。

**Comment by yanxyz** [comment]
明白了，@limichange 用的是 coding 的 pages 服务，我以为是你个人的服务器。

**Comment by limichange** [comment]
@yanxyz 就结果来说，效果不错。

**Comment by yanxyz** [comment]
coding 的 pages 更新不是即时的，要手动重启 pages……这两天 gitcafe 许多用户迁移到了 coding 上，国内做这个不容易，本身盈利困难，又有政策风险。还是看看国内谁愿意做镜像。

**Comment by limichange** [comment]
@yanxyz 感觉空欢喜一场

**Comment by yanxyz** [comment]
coding 更新暂时解决了，先观察一阵子。

**Comment by yyx990803** [comment]
@limichange @yanxyz vuejs.org.cn 好像挂了？现在会直接跳到 coding.net 的页面去。

**Comment by yanxyz** [comment]
@yyx990803 是 coding.net 发烧了。这两天他们在迁移 gitcafe 的用户，出了一些问题，不知道后面怎么样。

**Comment by limichange** [comment]
现在应该是好了，真是囧。

**Comment by febobo** [comment]
www.vue-js.com 尤大， 你看这域名怎么样 ？ 这个去年就开始在搞 vue国内社区了 ，不过也由于自身时间问题缺少管理运营的不是很理想，访问速度倒是秒开， 同意我将文档扔一份上去吗 ？

**Comment by yanxyz** [comment]
在你的网站上放一份没问题。不过正式的中文网站只有 cn.vuejs.org 这个，以这个网站为准。

**Comment by stackOverMind** [comment]
我们的bgp 机房速度很快，愿意免费提供帮助

**Comment by stackOverMind** [comment]
@yyx990803 @yanxyz  我们有自己的bgp机房，访问速度很好，需要的话随时提供帮助

**Comment by Jinjiang** [comment]
鉴于现在国内网站备案流程比较复杂，而且需要在申请期间中断域名的访问，这对于已经比较流行且流量可观的 vuejs.org 来说几乎是不可能的，所以经过一番了解和调研之后，决定还是暂时保持现状。

如果有更好的建议我们可以再开贴讨论。
谢谢大家的支持和建议

**Comment by zhangpeng2k** [comment]
> http://vuejs.org.cn 😊
😇
在公司，好奇点了一下...点进去居然是个黄网
