### ISSUE TITLE
this.error && this.error.type === 'fatal' 这个是什么意思 希望可以注释一下

### ISSUE THREAD

**Issue by Longx** [vuejs/cn.vuejs.org#892]

**Comment by Justineo** [comment]
这是 JS 基本的表达式，我不认为 Vue 的文档里面需要对 JS 的基本用法添加注释。

**Comment by Longx** [comment]
js好像没有出现fatal这个类型吧  error如果为null的，整个表达式的结果是null不应该是返回boolean值吗？而单单使用this.error.type会报错，没太能明白这个表达式的意思，望帮忙解释一下，非常感谢！

**Comment by Justineo** [comment]
这里的 `error` 是一个自定义的普通对象，用户自己设置的。

**Comment by Longx** [comment]
如果只是把error转为boolean值，直接!error就可以了  为什么要有this.error.type ===‘fatal’这一部分呢

**Comment by Justineo** [comment]
这不是这个例子的重点……这里对应的 case 就是假设只在 `type === 'fatal'` 时才设置对应的 `class`。

**Comment by Longx** [comment]
额  好吧，我好像有点钻牛角尖了，不过如果在这个case后面加上“假设只在 type === 'fatal' 时才设置对应的 class”应该会更好，方便用户快速理解

**Comment by Longx** [comment]
感谢你的耐心解答，谢谢！

**Comment by karry1155** [comment]
感谢二位！

**Comment by xiaoshanzhaguo** [comment]
感谢，明白了！

**Comment by geg98779** [comment]
感谢 还以为是js中的内置对象

**Comment by congfamin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
