### ISSUE TITLE
css－style  autoprefixer 失效

### ISSUE THREAD

**Issue by shawushe** [vuejs/cn.vuejs.org#91]
您好，最近在了解vue，遇到一个问题：如题描述，厂商前缀没有生效不是为何，
<div v-bind:style="{ color:activeColor, fontSize: fontSize + 'px',borderRadius:'5px',display:'flex' }">纯内嵌</div>
经vue编译渲染后，没有达到预期效果，望指教

**Comment by yyx990803** [comment]
请提供更详细的描述，比如用的是 vueify 还是 vue-loader，什么版本，带上代码。这么简单的描述没法帮你。另外请把 issue 开到对应工具的仓库而不是这里。
