### ISSUE TITLE
请问vue.js文档是用什么工具生成的吗？

### ISSUE THREAD

**Issue by xtzero** [vuejs/cn.vuejs.org#912]
# 请问vue.js文档是用什么工具生成的吗？

十分喜欢vue.js官方文档的风格，以为是用gitbook生成的，但没有找到相关的内容。想问下**vue.js文档是用什么工具生成的吗？**

**Comment by Justineo** [comment]
[Hexo](https://hexo.io/zh-cn/).

![image](https://user-images.githubusercontent.com/1726061/56857997-48e58600-69a6-11e9-9c41-67f66d2becf6.png)

**Comment by xtzero** [comment]
thx

**Comment by xtzero** [comment]
想知道具体用了哪些插件，可以给一个列表嘛

**Comment by Justineo** [comment]
整个项目都在这里了，还要怎么列……

**Comment by xtzero** [comment]
啊~明白了
感谢大大回复
