### ISSUE TITLE
VuePress Migration Feedback

### ISSUE THREAD

**Issue by bencodezen** [vuejs/cn.vuejs.org#916]
Hello! 

My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.

As maintainers for the Chinese translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.

Looking forward to your response!

**Comment by Jinjiang** [comment]
Hi Ben, very glad to hear that!

Nothing big deal for the Chinese translation site, should just care about a few things that not exactly the same to the English site:
- There are some third-party resources blocked in China. So we have to find ways to exchange them (e.g. Google, Vimeo).
- There are some Chinese special sponsors only displayed on the Chinese site. So the template/config of the theme is a little different.

One more question is: after the update, would all the languages be in one repo or just be kept in separate repos like now?

Thanks.

@Justineo any ideas or complement?

**Comment by bencodezen** [comment]
Hey @Jinjiang! 

Thanks for the heads up. We will be sure to keep those in mind during the migration. 

To answer your question, they will continue to be managed in separate repos to allow translators to maintain control and have easier time managing things.

Let me know if you have any other thoughts or ideas in the meantime!

**Comment by Justineo** [comment]
As I know currently VuePress works as an SPA even across different languages. If we keep translations in separate repos we may need to use some CI process to combine them into a single site.

**Comment by Jinjiang** [comment]
> As I know currently VuePress works as an SPA even across different languages. If we keep translations in separate repos we may need to use some CI process to combine them into a single site.

Yes, and if we choose across-language SPA solution, the URL might be changed into vuejs.org/zh as I understand. So the 2 solutions both have pros and cons IMO. No worry, I just make a confirmation. Keeping separate repos is good. :-)

Thanks.

**Comment by bencodezen** [comment]
@Justineo No concerns there since we don't plan on forcing everyone into a single site at this time. We'll let you know if plans change!

**Comment by temuiphone** [comment]
GOOD!

**Comment by misitebao** [comment]
I was going to clone it and translate it before, but I found out that it was not based on vuepress. I was surprised at that time. Later I thought it might be because vuepress hadn't appeared when the first version of the document was written.

**Comment by ShenQingchuan** [comment]
Hi，@JinJiang
I am the guy who helped the Composition API RFC's translation, and I saw #1116 the great work of @veaba,
but seems there're a lot problem to be solved:

1. first, the translation needs to be checked and according to my last journey of contribution, it may cost **a lot** time.
   No offence, but in my opinion, the #1116's version is still not good enough, but I really respect that huge work.
2. for Advertisement, the Chinese Docs are different from the English version, some sponsorships need their blocks inside the cn.vuejs.org like DCloud/iMooc（慕课网）
3. for Codepen.io demos，there are lots of demo that contains some guidance text, **it actually is a big part of the documentation !!**, so we need to maintain our own Chinese version demos' collection.

I provide a fork for docs-next, but I didn't catch so fast as #1116, but in my deploying site, I am trying my best to maintain the similarity between mine and cn.vuejs.org.

My fork address: [Click Here](https://github.com/ShenQingchuan/docs-next)

If anyone interested in translation projects, maybe we can start from here to seek how we can migration Hexo to Vuepress for cn.vuejs.org.

**Comment by Jinjiang** [comment]
All, we already created a new repo for Vue 3.0 Chinese doc site. https://github.com/vuejs/docs-next-zh-cn
Currently, there is still a lot of translation and review work that needs all your help. So I'd like to invite all of you to join.

Actually, this repo is based on @veaba 's previous great job #1116.

@ShenQingchuan thanks for your advice, I suggest we join the translation and review work together on our new repo.

Thanks.
