### ISSUE TITLE
quote翻译问题

### ISSUE THREAD

**Issue by marshcat0** [vuejs/cn.vuejs.org#920]
在[绑定内联样式](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax-1)这里，有一句

> You can use either camelCase or kebab-case (use quotes with kebab-case) for the CSS property names:

其中‘’use quotes‘’在中文翻译中翻译成了‘’用单引号‘’。如果内联样式最外边的引号是单引号的话，我觉得kebab-case用双引号也是可以的吧。
所以应该翻译成引号？没有实际试过所以来提个issue

**Comment by Justineo** [comment]
> 所以应该翻译成引号？

我理解是的。
