### ISSUE TITLE
插槽网页内容和源码不同

### ISSUE THREAD

**Issue by YongzeYao** [vuejs/cn.vuejs.org#931]
插槽的源码文件中，“其他示例”代码如下：
![image](https://user-images.githubusercontent.com/22460339/58736811-07d0ff00-83b4-11e9-8e33-26c38ae3e525.png)
但是，网页显示如下：
![image](https://user-images.githubusercontent.com/22460339/58736835-16b7b180-83b4-11e9-8323-f6bb8e0a4168.png)
少了一个name="todo"。

**Comment by Jinjiang** [comment]
https://github.com/vuejs/cn.vuejs.org/pull/870/files

**Comment by Jinjiang** [comment]
三个月前就改好了，你可以做个二次确认
