### ISSUE TITLE
示例页用的jsfiddle 已经打不开了

### ISSUE THREAD

**Issue by cranux** [vuejs/cn.vuejs.org#932]
jsfiddle.net  打不开
![image](https://user-images.githubusercontent.com/37317831/58763059-06a4fb00-8589-11e9-93da-96b393739ecf.png)

**Comment by walkingon** [comment]
同样打不开，北京。
`localhost:~ xes$ ping jsfiddle.net
PING jsfiddle.net (45.55.126.88): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3`

**Comment by huanghe2015** [comment]
应该是被墙了。。。。

**Comment by Jinjiang** [comment]
Hi, 目前官网所有 jsfiddle 的例子都已经换成了 codesandbox，理论上是可以正常访问了。如果仍有问题可以重开 issue 单独讨论。谢谢
