### ISSUE TITLE
Inaccuracy in comparisons guide

### ISSUE THREAD

**Issue by wsad56897** [vuejs/cn.vuejs.org#944]
Vue的开发团队：
     你们好，我是一名使用react的开发者，也在尝试学习你们的Vue，看了你们那篇Vue与其他框架的对比 。
![image](https://user-images.githubusercontent.com/20641232/59843356-fcf20480-938a-11e9-9f91-e69d54266e59.png)，
对于这点有些疑惑为啥需要保证组件的整个子树的渲染输出都要由该组件的 props 所决定，PureComponent的缺点不是props对比是浅比较，如果父组件的props传过来的是一个改变的对象而不改变引用就检测不到吗，或者是在render方法里传来的对象引用不同但是内容一样

**Comment by Jinjiang** [comment]
@phanan this Chinese question is asking about our comparison page. When describing the `PureComponent` in React. Our comparison page says "assumes the entire sub tree’s render output is determined by the props of the current component". But actually the truth is the [`PureComponent` implements it with a *shallow prop and state comparison*](https://reactjs.org/docs/react-api.html#reactpurecomponent).

So just kindly wanna make a confirm.

/ping @yyx990803 

Thanks.

**Comment by yyx990803** [comment]
> 传过来的是一个改变的对象而不改变引用就检测不到

子树里面如果用了 context，也会导致更新被 PureComponent 阻挡。
