### ISSUE TITLE
Vue-cli安装失败,怎么解决

### ISSUE THREAD

**Issue by yimchengjie** [vuejs/cn.vuejs.org#949]
Node.js 和npm都安装过了
![ER4X9LZ%IY}Y}8EI@`3~I_6](https://user-images.githubusercontent.com/43691246/60324061-4b6c5800-99b6-11e9-8905-9b552dd943d9.png)
然后安装vue-cli就出问题
![4SI5EFR5FJ)AP5MT28ERV2H](https://user-images.githubusercontent.com/43691246/60324085-617a1880-99b6-11e9-8f43-a6eacf7635b8.png)

**Comment by Justineo** [comment]
本项目只负责英文文档的同步翻译，不负责解决用法的问题，有疑问请前往[论坛](https://forum.vuejs.org/)、[StackOverflow](https://stackoverflow.com/questions/tagged/vue.js) 或者 [Discord 聊天室](https://chat.vuejs.org/) 请求帮助，谢谢。
