### ISSUE TITLE
The animation of 'Look at me' example doesn't work in Chrome and Firefox on page transitions.html

### ISSUE THREAD

**Issue by snowffer** [vuejs/cn.vuejs.org#95]
When click Toggle button, there should be an shrink-magnify animation, but it doesn't. Just hold on for a sec and then appear-disappear.

But it works for IE11

Chrome version is 48.0.2564.109 m
Firefox version is 43.0.1

**Comment by yyx990803** [comment]
Fixed. For some reason `transform: scale` no longer works on inline elements (must be `inline-block` or `block`)
