### ISSUE TITLE
[译法讨论] “逆转消息”是否翻译成”反转消息“更好？

### ISSUE THREAD

**Issue by injune1123** [vuejs/cn.vuejs.org#953]
一个非常小的建议：
原有译法”逆转消息“不太符合中文的表达，建议翻译成”反转消息“。理由是”逆转“也含有”情势恶化“等抽象语义，而”反转“更为中性，”反转“是”Reverse“的常见翻译，例如"Reverse String" 会变翻译成”反转字符串“。
PR：https://github.com/vuejs/cn.vuejs.org/pull/952

**Comment by Justineo** [comment]
谢谢，已合入。
