### ISSUE TITLE
v-if 和v-show指令放在一个包裹的div或section可以切换多个元素吧?

### ISSUE THREAD

**Issue by SansaZhang** [vuejs/cn.vuejs.org#97]
v-if 和v-show指令放在一个包裹的div或section可以切换多个元素吧?

**Comment by yyx990803** [comment]
你试一下不就知道了？

**Comment by SansaZhang** [comment]
恩 ,试过发现v-if 不可以放在根元素上,外面需要再加一层结构包裹或者直接用<template>..v-show可以直接放在根元素.
