### ISSUE TITLE
Vuex Mistyping in document comments

### ISSUE THREAD

**Issue by temuiphone** [vuejs/cn.vuejs.org#986]
URL:   https://vuex.vuejs.org/zh/guide/actions.html

For more information, please refer to the picture.
https://ae01.alicdn.com/kf/H82f25e7732b24d2daf96164fa46ec0c4h.jpg

**Comment by Jinjiang** [comment]
没问题，原文是 optimistically。就是乐观的意思，言外之意是 checkout 有失败的风险，但是这里演示考虑就假定一定可以成功。

**Comment by Justineo** [comment]
可以了解一下 Optimistic UI :)
