### ISSUE TITLE
关于.capture修饰符的翻译

### ISSUE THREAD

**Issue by liumulin614** [vuejs/cn.vuejs.org#988]
英文的原文解释为：an event targeting an inner element is handled here before being handled by that element，中文翻译为：即**元素自身**触发的事件先在此处理，然后才交由内部元素进行处理。
但是根据英文原文的意思，结合事件捕获的概念，是不是翻译成：“即内部元素触发的事件先在此处理，然后才交由内部元素进行处理”更合适一些？

**Comment by Justineo** [comment]
我理解是的，欢迎 PR

**Comment by Justineo** [comment]
Fixed in #989.
